'use strict';var e,k="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},l="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,aa=function(){aa=function(){};l.Symbol||(l.Symbol=ba)},ba=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),m=function(){aa();var a=l.Symbol.iterator;a||(a=l.Symbol.iterator=l.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&
k(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(this)}});m=function(){}},ca=function(a){var b=0;return da(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},da=function(a){m();a={next:a};a[l.Symbol.iterator]=function(){return this};return a},r=function(a){m();var b=a[Symbol.iterator];return b?b.call(a):ca(a)},ea=function(a,b){if(b){var c=l;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&
null!=b&&k(c,a,{configurable:!0,writable:!0,value:b})}};
ea("String.prototype.startsWith",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var b=this+"";a+="";var f=b.length,g=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var h=0;h<g&&c<f;)if(b[c++]!=a[h++])return!1;return h>=g}},"es6","es3");
var fa=this,t=function(a,b,c){a=a.split(".");c=c||fa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b},u=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},v=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,g){for(var d=Array(arguments.length-
2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[c].apply(a,d)}};var w=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));this.reportErrorToServer=!0};v(w,Error);w.prototype.name="CustomError";var x=function(a,b){for(var c=a.split("%s"),d="",f=c.length-1,g=0;g<f;g++)d+=c[g]+(g<b.length?b[g]:"%s");w.call(this,d+c[f]);this.messagePattern=a};v(x,w);x.prototype.name="AssertionError";var y=function(a,b){throw new x("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var z=function(){this.privateDoNotAccessOrElseSafeScriptWrappedValue_="";this.SAFE_SCRIPT_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_=ha};z.prototype.implementsGoogStringTypedString=!0;var ha={};z.prototype.getTypedStringValue=function(){return this.privateDoNotAccessOrElseSafeScriptWrappedValue_};z.prototype.toString=function(){return"SafeScript{"+this.privateDoNotAccessOrElseSafeScriptWrappedValue_+"}"};
var ia=function(a){if(a instanceof z&&a.constructor===z&&a.SAFE_SCRIPT_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_===ha)return a.privateDoNotAccessOrElseSafeScriptWrappedValue_;y("expected object of type SafeScript, got '"+a+"' of type "+u(a));return"type_error:SafeScript"};z.prototype.goog_html_SafeScript_prototype$initSecurityPrivateDoNotAccessOrElse_=function(a){this.privateDoNotAccessOrElseSafeScriptWrappedValue_=a;return this};var A=function(){this.privateDoNotAccessOrElseTrustedResourceUrlWrappedValue_="";this.TRUSTED_RESOURCE_URL_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_=ja};e=A.prototype;e.implementsGoogStringTypedString=!0;e.getTypedStringValue=function(){return this.privateDoNotAccessOrElseTrustedResourceUrlWrappedValue_};e.implementsGoogI18nBidiDirectionalString=!0;e.getDirection=function(){return 1};
e.cloneWithParams=function(a){var b=B(this),c=/\?/.test(b)?"&":"?",d;for(d in a)for(var f="array"==u(a[d])?a[d]:[a[d]],g=0;g<f.length;g++)null!=f[g]&&(b+=c+encodeURIComponent(d)+"="+encodeURIComponent(String(f[g])),c="&");a=new A;a.privateDoNotAccessOrElseTrustedResourceUrlWrappedValue_=b;return a};e.toString=function(){return"TrustedResourceUrl{"+this.privateDoNotAccessOrElseTrustedResourceUrlWrappedValue_+"}"};
var B=function(a){if(a instanceof A&&a.constructor===A&&a.TRUSTED_RESOURCE_URL_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_===ja)return a.privateDoNotAccessOrElseTrustedResourceUrlWrappedValue_;y("expected object of type TrustedResourceUrl, got '"+a+"' of type "+u(a));return"type_error:TrustedResourceUrl"},ja={};var C=function(a,b){if(b)a=a.replace(ka,"&amp;").replace(la,"&lt;").replace(ma,"&gt;").replace(na,"&quot;").replace(oa,"&#39;").replace(pa,"&#0;");else{if(!qa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ka,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(la,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ma,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(na,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(oa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(pa,"&#0;"))}return a},ka=/&/g,la=/</g,ma=/>/g,na=/"/g,oa=/'/g,
pa=/\x00/g,qa=/[\x00&<>"']/;var D=function(){this.goog_html_SafeUrl$privateDoNotAccessOrElseSafeHtmlWrappedValue_="";this.SAFE_URL_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_=ra};e=D.prototype;e.implementsGoogStringTypedString=!0;e.getTypedStringValue=function(){return""};e.implementsGoogI18nBidiDirectionalString=!0;e.getDirection=function(){return 1};e.toString=function(){return"SafeUrl{}"};
var sa=function(a){if(a instanceof D&&a.constructor===D&&a.SAFE_URL_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_===ra)return"";y("expected object of type SafeUrl, got '"+a+"' of type "+u(a));return"type_error:SafeUrl"},ra={};var E=function(){this.privateDoNotAccessOrElseSafeStyleWrappedValue_="";this.SAFE_STYLE_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_=ta};E.prototype.implementsGoogStringTypedString=!0;var ta={};E.prototype.getTypedStringValue=function(){return this.privateDoNotAccessOrElseSafeStyleWrappedValue_};E.prototype.toString=function(){return"SafeStyle{"+this.privateDoNotAccessOrElseSafeStyleWrappedValue_+"}"};
var ua=function(a){if(a instanceof E&&a.constructor===E&&a.SAFE_STYLE_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_===ta)return a.privateDoNotAccessOrElseSafeStyleWrappedValue_;y("expected object of type SafeStyle, got '"+a+"' of type "+u(a));return"type_error:SafeStyle"};E.prototype.goog_html_SafeStyle_prototype$initSecurityPrivateDoNotAccessOrElse_=function(a){this.privateDoNotAccessOrElseSafeStyleWrappedValue_=a;return this};var F=function(){this.goog_html_SafeHtml$privateDoNotAccessOrElseSafeHtmlWrappedValue_="";this.SAFE_HTML_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_=va;this.dir_=null};e=F.prototype;e.implementsGoogI18nBidiDirectionalString=!0;e.getDirection=function(){return this.dir_};e.implementsGoogStringTypedString=!0;e.getTypedStringValue=function(){return this.goog_html_SafeHtml$privateDoNotAccessOrElseSafeHtmlWrappedValue_};
e.toString=function(){return"SafeHtml{"+this.goog_html_SafeHtml$privateDoNotAccessOrElseSafeHtmlWrappedValue_+"}"};var wa=function(a){if(a instanceof F&&a.constructor===F&&a.SAFE_HTML_TYPE_MARKER_GOOG_HTML_SECURITY_PRIVATE_===va)return a.goog_html_SafeHtml$privateDoNotAccessOrElseSafeHtmlWrappedValue_;y("expected object of type SafeHtml, got '"+a+"' of type "+u(a));return"type_error:SafeHtml"},va={};
F.prototype.goog_html_SafeHtml_prototype$initSecurityPrivateDoNotAccessOrElse_=function(a,b){this.goog_html_SafeHtml$privateDoNotAccessOrElseSafeHtmlWrappedValue_=a;this.dir_=b;return this};t("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.implementsGoogStringTypedString?!0:!1},void 0);t("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0},void 0);t("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof A)return B(a);if(a instanceof F)return wa(a);if(a instanceof D)return sa(a);if(a instanceof E)return ua(a);if(a instanceof z)return ia(a);throw Error();},void 0);
t("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return wa(b);if("resourceUrl"==a||"templateUrl"==a)return B(b);if("url"==a)return b instanceof A?B(b):sa(b);if("css"==a)return ua(b);if("js"==a)return ia(b);throw Error();},void 0);var G=["NONE","ERROR","WARNING","INFO","DEBUG"],ya={cep_proxy_url:!0,enable_auto_enrollment:!0,enable_certificate_renewal:!0,allow_machine_cert_enrollment:!0,user_enrollment_templates:!0,device_enrollment_templates:!0,placeholder_values:!0,company_info:!0,log_level:!0,device_cert_request_values:!0,signature_algo:!0,pending_ui_enabled:!0,renew_hours_before_expiry:!0,renew_reminder_interval:!0,request_timeout_seconds:!0,va_api_key:!0,va_enabled:!0,va_google_url:!0,va_shared_secret:!0,va_request_timeout_seconds:!0},
H=G.indexOf("ERROR"),I=G.indexOf("WARNING"),J=G.indexOf("INFO"),K=G.indexOf("DEBUG"),za="",L=function(a,b,c){0<b&&b<=c&&b<G.length&&(a=G[b]+": "+a,console.log(a),za+="\n"+a)},Aa=function(a){var b="";a=new Uint8Array(a);for(var c=0;c<a.length;c++)b+=String.fromCharCode(a[c]);return b},Ba=function(a){for(var b=a.length,c=new ArrayBuffer(b),d=new Uint8Array(c),f=0;f<b;f++)d[f]=a.charCodeAt(f);return c},M=function(a,b){var c="";a=a.getElementsByTagName(b);null!=a&&void 0!=a&&0!=a.length&&(c=a[a.length-
1].innerHTML);if(null==c||void 0==c)c="";return c},Ca=function(a){chrome.alarms.getAll(function(b){for(var c=0;c<b.length;c++){var d=b[c],f=JSON.parse(d.name);f.name&&f.name==a&&chrome.alarms.clear(d.name)}})},Da=function(a,b){return a.replace(/\${(.+?)(:"(.+?)")?}/g,function(a,d,f,g){a=d.split(":");for(d=0;d<a.length;++d)if(f=a[d],f in b&&b[f])return b[f];return g?g:""})};var N=function(a,b,c,d,f,g){this.isRequestingNewCertificate_=!0;this.deviceWideCheckboxText=this.h2Text=this.enrollOrCheckStatusButtonText=this.showOrHidePendingRequestText="";this.deviceWideCheckboxDisabled=!1;this.passwordValue=this.usernameValue=this.passwordFormFieldPlaceholder=this.usernameFormFieldPlaceholder="";this.isUserRequestingDeviceWideCertValue=!1;this.checkStatusButtonText_=this.requestIdValue=this.requestIdFormFieldPlaceholder=this.uriValue=this.uriFormFieldPlaceholder=this.loginButtonText_=
"";this.invalidCharacterText=chrome.i18n.getMessage("login_invalid_character");this.helpLabelText=this.helpText=this.helpUrl=this.moreOptionsValue=this.moreOptionsText="";this.pendingUIEnabled=!0;this.copyToClipboardButtonText=this.licenseNoticeButtonText="";this.showPendingRequestText_=chrome.i18n.getMessage("login_show_pending");this.hidePendingRequestText_=chrome.i18n.getMessage("login_hide_pending");this.privacyLinkText=chrome.i18n.getMessage("login_privacy_link");this.helpCenterText=chrome.i18n.getMessage("login_help_center_text");
this.deviceWideHelpText=chrome.i18n.getMessage("login_device_help");this.loadingText=chrome.i18n.getMessage("login_loading_text");this.companyLogo=this.companyName="";this.managedPolicyService_=a;this.tokenService_=b;this.certificatePolicyService_=c;this.certificateSavingService_=d;this.enrollmentAgentService_=f;this.mdDialog_=g;var h=this;this.managedPolicyService_.requestPolicyUpdate().then(function(){h.setFormValuesFromManagedPolicy_()},function(){})};t("ccr.controllers.LoginPageCtrl",N,void 0);
N.$inject="managedPolicyService tokenService certificatePolicyService certificateSavingService enrollmentAgentService $mdDialog".split(" ");N.prototype.failureAlert_=function(a){L(a,H,this.managedPolicyService_.getLogLevel());this.notify_(chrome.i18n.getMessage("failure_title"),chrome.i18n.getMessage("login_failure_alert"),!0)};
N.prototype.pendingAlert_=function(a,b,c){L(a,J,this.managedPolicyService_.getLogLevel());""===this.requestIdValue&&""===this.uriValue&&(this.requestIdValue=b,this.uriValue=c);this.notify_(chrome.i18n.getMessage("pending_title"),a,!0)};N.prototype.notify_=function(a,b,c){var d=chrome.i18n.getMessage("okay_button");a=this.mdDialog_.alert().title(a).htmlContent(b).ok(d);c&&this.hideProgress_();this.mdDialog_.show(a)};
N.prototype.resetOnEscape=function(){-1==document.getElementById("moreOptionsMenu").className.indexOf("md-open")&&this.removeNegativeTabIndexes()};N.prototype.resetOnEscape=N.prototype.resetOnEscape;N.prototype.setNegativeTabIndexes=function(){this.setTabIndexes_("-1")};N.prototype.setNegativeTabIndexes=N.prototype.setNegativeTabIndexes;N.prototype.removeNegativeTabIndexes=function(){this.setTabIndexes_("")};N.prototype.removeNegativeTabIndexes=N.prototype.removeNegativeTabIndexes;
N.prototype.setTabIndexes_=function(a){for(var b=document.getElementsByClassName("elementToHideWhenMenuIsOpen"),c=0;c<b.length;c++)b[c].setAttribute("tabindex",a);document.getElementById("checkboxToHideWhenMenuIsOpen").setAttribute("tabindex","-1"===a?"-1":"0")};N.prototype.startProgress_=function(a){document.getElementsByClassName("hiddenProgressCircular")[a].style.visibility="visible"};
N.prototype.hideProgress_=function(){for(var a=document.getElementsByClassName("hiddenProgressCircular"),b=0;b<a.length;b++)a[b].style.visibility="hidden"};N.prototype.showLicense=function(){this.mdDialog_.show({controller:"ccr.controllers.LoginPageCtrl",templateUrl:"../html/notice.html",clickOutsideToClose:!0})};N.prototype.showLicense=N.prototype.showLicense;
N.prototype.copyToClipboard=function(){var a=document.createElement("input");a.style.position="fixed";a.style.zIndex="-1";a.value=za;document.body.appendChild(a);a.select();document.execCommand("copy");document.body.removeChild(a)};N.prototype.copyToClipboard=N.prototype.copyToClipboard;
N.prototype.showHelpText=function(){var a="../html/help_text_anchor.html";""===this.helpText&&(a="../html/help_anchor.html");this.mdDialog_.show({controller:"ccr.controllers.LoginPageCtrl",templateUrl:a,clickOutsideToClose:!0,parent:angular.element(document.body)})};N.prototype.showHelpText=N.prototype.showHelpText;
N.prototype.setFormValuesFromManagedPolicy_=function(){this.h2Text=this.managedPolicyService_.getLoginPageHeaderText();this.deviceWideCheckboxText=this.managedPolicyService_.getLoginPageDeviceWideCheckboxText();this.deviceWideCheckboxDisabled=!this.managedPolicyService_.isMachineCertEnrollmentAllowed();this.usernameFormFieldPlaceholder=this.managedPolicyService_.getUsernameFormFieldPlaceholder();this.passwordFormFieldPlaceholder=this.managedPolicyService_.getPasswordFormFieldPlaceholder();this.loginButtonText_=
this.managedPolicyService_.getLoginPageLoginButtonText();this.uriFormFieldPlaceholder=this.managedPolicyService_.getUriFormFieldPlaceholder();this.requestIdFormFieldPlaceholder=this.managedPolicyService_.getRequestIdFormFieldPlaceholder();this.checkStatusButtonText_=this.managedPolicyService_.getLoginPageStatusButtonText();this.moreOptionsText=this.managedPolicyService_.getLoginPageMoreOptionsText();this.helpUrl=this.managedPolicyService_.getHelpUrl();this.helpText=this.managedPolicyService_.getHelpText();
this.helpLabelText=this.managedPolicyService_.getLoginPageHelpLabelText();this.licenseNoticeButtonText=this.managedPolicyService_.getLoginPageLicenseButtonText();this.copyToClipboardButtonText=this.managedPolicyService_.getLoginPageClipboardButtonText();this.companyName=this.managedPolicyService_.getCompanyName();this.companyLogo=this.managedPolicyService_.getCompanyLogo();this.pendingUIEnabled=this.managedPolicyService_.isPendingUIEnabled();this.showOrHidePendingRequestText=this.showPendingRequestText_;
this.enrollOrCheckStatusButtonText=this.loginButtonText_};
N.prototype.flipBetweenSubmitAndCheck=function(){if(this.isRequestingNewCertificate_){var a=document.getElementById("extraFieldsForCheckStatus");a.className="showExtraFieldsForCheckStatus";a=document.getElementById("mainCard");a.className=a.className.replace("smallMainCard","bigMainCard").trim();a=document.getElementsByClassName("inputsRequiredForPendingRequest");for(var b=0;b<a.length;b++)a[b].setAttribute("required","");this.showOrHidePendingRequestText=this.hidePendingRequestText_;this.enrollOrCheckStatusButtonText=
this.checkStatusButtonText_;this.isRequestingNewCertificate_=!1}else{a=document.getElementById("extraFieldsForCheckStatus");a.className="hideExtraFieldsForCheckStatus";a=document.getElementById("mainCard");a.className=a.className.replace("bigMainCard","smallMainCard").trim();a=document.getElementsByClassName("inputsRequiredForPendingRequest");for(b=0;b<a.length;b++)a[b].removeAttribute("required");this.showOrHidePendingRequestText=this.showPendingRequestText_;this.enrollOrCheckStatusButtonText=this.loginButtonText_;
this.isRequestingNewCertificate_=!0}};N.prototype.flipBetweenSubmitAndCheck=N.prototype.flipBetweenSubmitAndCheck;N.prototype.decideEnrollmentRequest=function(){this.managedPolicyService_.isVerifiedAccessEnabled()?this.submitVaForm_():this.isRequestingNewCertificate_?this.submitForm_():this.queryStatus_()};N.prototype.decideEnrollmentRequest=N.prototype.decideEnrollmentRequest;e=N.prototype;
e.submitVaForm_=function(){var a=this;L("Submit button triggered with va.",J,this.managedPolicyService_.getLogLevel());var b=C(this.usernameValue,!1),c=C(this.passwordValue,!1);if(""===b)a.notify_(chrome.i18n.getMessage("failure_title"),chrome.i18n.getMessage("empty_username"),!0);else{var d="",f=this.managedPolicyService_.getCepProxyUrl(),g=this.managedPolicyService_.getUserEnrollmentTemplates();this.startProgress_(0);a.tokenService_.setTokenFromPlatformKeys(a.isUserRequestingDeviceWideCertValue).then(function(){void 0===
a.tokenService_.getCurrentToken()?(d=a.tokenService_.ccr_services_Token_prototype$getErrorMessage(),a.notify_(chrome.i18n.getMessage("failure_title"),d,!0)):a.enrollToGivenEndpoint_(a.enrollmentAgentService_,f,g,b,c)},function(){d=a.tokenService_.ccr_services_Token_prototype$getErrorMessage();a.notify_(chrome.i18n.getMessage("failure_title"),d,!0)})}};
e.submitForm_=function(){var a=this;L("Submit button triggered.",J,a.managedPolicyService_.getLogLevel());var b=C(this.usernameValue,!1),c=C(this.passwordValue,!1);if(""===b)a.notify_(chrome.i18n.getMessage("failure_title"),chrome.i18n.getMessage("empty_username"),!0);else{var d="";this.startProgress_(0);a.tokenService_.setTokenFromPlatformKeys(a.isUserRequestingDeviceWideCertValue).then(function(){void 0===a.tokenService_.getCurrentToken()?(d=a.tokenService_.ccr_services_Token_prototype$getErrorMessage(),
a.notify_(chrome.i18n.getMessage("failure_title"),d,!0)):a.certificatePolicyService_.contactPolicyServer(b,c).then(function(){var f=a.certificatePolicyService_.getAllEnrollmentUris();0<f.length?a.enrollToEachEndpointTuple_(f,b,c):(d=chrome.i18n.getMessage("login_no_uri_failure"),a.failureAlert_(d))},function(){a.certificatePolicyService_.isSpecificErrorPresent()?a.notify_(chrome.i18n.getMessage("failure_title"),a.certificatePolicyService_.ccr_services_RequestService_prototype$getErrorMessage(),!0):
a.failureAlert_(chrome.i18n.getMessage("login_cep_failure"))})},function(){d=a.tokenService_.ccr_services_Token_prototype$getErrorMessage();a.notify_(chrome.i18n.getMessage("failure_title"),d,!0)})}};e.enrollToEachEndpointTuple_=function(a,b,c){a=a.shift();this.enrollToGivenEndpoint_(this.certificateSavingService_,a.uri,[a.name],b,c)};
e.enrollToGivenEndpoint_=function(a,b,c,d,f){var g=this,h="";a.enroll(b,d,f,c).then(function(){a.isEnrolledSuccessfully()?g.notify_(chrome.i18n.getMessage("success_title"),chrome.i18n.getMessage("login_success_alert"),!0):a.isRequestPending()?(h=a.ccr_services_RequestService_prototype$getErrorMessage(),g.pendingAlert_(h,a.getPendingRequestId(),a.getPendingRequestUri())):(h=a.ccr_services_RequestService_prototype$getErrorMessage(),g.failureAlert_(h))},function(){a.isSpecificErrorPresent()?g.notify_(chrome.i18n.getMessage("failure_title"),
a.ccr_services_RequestService_prototype$getErrorMessage(),!0):g.failureAlert_(chrome.i18n.getMessage("login_enrollment_failure"))})};
e.queryStatus_=function(){var a=this;L("Query status button triggered.",J,this.managedPolicyService_.getLogLevel());if(null!=this.uriValue&&void 0!=this.uriValue&&this.uriValue.startsWith("https://")){var b=C(this.usernameValue,!1),c=C(this.passwordValue,!1),d=C(this.uriValue,!0),f=C(this.requestIdValue,!1),g=this.isUserRequestingDeviceWideCertValue,h="";this.startProgress_(1);this.tokenService_.setTokenFromPlatformKeys(g).then(function(){void 0===a.tokenService_.getCurrentToken()?(h=a.tokenService_.ccr_services_Token_prototype$getErrorMessage(),
a.notify_(chrome.i18n.getMessage("failure_title"),h,!0)):a.certificateSavingService_.checkPendingRequestStatus(d,f,b,c).then(function(){a.certificateSavingService_.isEnrolledSuccessfully()?a.notify_(chrome.i18n.getMessage("success_title"),chrome.i18n.getMessage("login_success_alert"),!0):a.certificateSavingService_.isRequestPending()?(h=a.certificateSavingService_.ccr_services_RequestService_prototype$getErrorMessage(),a.pendingAlert_(h,a.certificateSavingService_.getPendingRequestId(),a.certificateSavingService_.getPendingRequestUri())):
(h=a.certificateSavingService_.ccr_services_RequestService_prototype$getErrorMessage(),a.failureAlert_(h))},function(){a.certificateSavingService_.isSpecificErrorPresent()?a.notify_(chrome.i18n.getMessage("failure_title"),a.certificateSavingService_.ccr_services_RequestService_prototype$getErrorMessage(),!0):a.failureAlert_(chrome.i18n.getMessage("login_enrollment_failure"))})},function(){h=a.tokenService_.ccr_services_Token_prototype$getErrorMessage();a.notify_(chrome.i18n.getMessage("failure_title"),
h,!0)})}else this.notify_(chrome.i18n.getMessage("failure_title"),chrome.i18n.getMessage("login_query_uri"),!0)};var O=function(a,b){this.module$contents$ccr$services$CertRequestValues_CertRequestValues$managedPolicy_=a;this.module$contents$ccr$services$CertRequestValues_CertRequestValues$q_=b;this.replacements={}};e=O.prototype;e.doReplacementsOnSubject_=function(a){for(var b={},c=r(Ea),d=c.next();!d.done;d=c.next())d=d.value,d in a&&a[d]&&(b[d]=Da(a[d],this.replacements));return b};
e.doReplacementsOnSubjectAlternativeNames_=function(a){var b=[];a=r(a);for(var c=a.next();!c.done;c=a.next()){var d=c.value;"NameType"in d&&"Name"in d&&(c=d.NameType,d=Da(d.Name,this.replacements),b.push({NameType:c,Name:d}))}return b};
e.populateReplacements_=function(){var a=this,b=[],c=[];if(chrome&&chrome.enterprise&&chrome.enterprise.deviceAttributes){if(chrome.enterprise.deviceAttributes.getDirectoryDeviceId){c.push("enterprise.deviceAttributes.getDirectoryDeviceId");var d=this.module$contents$ccr$services$CertRequestValues_CertRequestValues$q_.defer();b.push(d.promise);chrome.enterprise.deviceAttributes.getDirectoryDeviceId(function(b){a.replacements.DEVICE_DIRECTORY_ID=b;d.resolve()})}if(chrome.enterprise.deviceAttributes.getDeviceAssetId){c.push("enterprise.deviceAttributes.getDeviceAssetId");
var f=this.module$contents$ccr$services$CertRequestValues_CertRequestValues$q_.defer();b.push(f.promise);chrome.enterprise.deviceAttributes.getDeviceAssetId(function(b){a.replacements.DEVICE_ASSET_ID=b;f.resolve()})}if(chrome.enterprise.deviceAttributes.getDeviceAnnotatedLocation){c.push("enterprise.deviceAttributes.getDeviceAnnotatedLocation");var g=this.module$contents$ccr$services$CertRequestValues_CertRequestValues$q_.defer();b.push(g.promise);chrome.enterprise.deviceAttributes.getDeviceAnnotatedLocation(function(b){a.replacements.DEVICE_ANNOTATED_LOCATION=
b;g.resolve()})}if(chrome.enterprise.deviceAttributes.getDeviceSerialNumber){c.push("enterprise.deviceAttributes.getDeviceSerialNumber");var h=this.module$contents$ccr$services$CertRequestValues_CertRequestValues$q_.defer();b.push(h.promise);chrome.enterprise.deviceAttributes.getDeviceSerialNumber(function(b){a.replacements.DEVICE_SERIAL_NUMBER=b;h.resolve()})}}if(chrome&&chrome.identity&&chrome.identity.getProfileUserInfo){c.push("chrome.identity.getProfileUserInfo");var p=this.module$contents$ccr$services$CertRequestValues_CertRequestValues$q_.defer();
b.push(p.promise);chrome.identity.getProfileUserInfo(function(b){b=b.email;a.replacements.USER_EMAIL=b;var c="",d=b.lastIndexOf("@");-1!=d&&(c=b.substring(d+1));a.replacements.USER_DOMAIN=c;p.resolve()})}L("Found the following APIs: "+c.join(),K,this.module$contents$ccr$services$CertRequestValues_CertRequestValues$managedPolicy_.getLogLevel());return this.module$contents$ccr$services$CertRequestValues_CertRequestValues$q_.all(b)};
e.logAvailableReplacements_=function(){for(var a=[],b=r(Object.keys(this.replacements)),c=b.next();!c.done;c=b.next())c=c.value,this.replacements[c]?a.push(c):a.push(c+" (no value)");L("Available placeholders: "+a.join(),K,this.module$contents$ccr$services$CertRequestValues_CertRequestValues$managedPolicy_.getLogLevel())};
e.module$contents$ccr$services$CertRequestValues_CertRequestValues_prototype$getDeviceCertRequestValues=function(){var a=this,b=this.module$contents$ccr$services$CertRequestValues_CertRequestValues$q_.defer();this.populateReplacements_().then(function(){var c=a.module$contents$ccr$services$CertRequestValues_CertRequestValues$managedPolicy_.ccr_services_ManagedPolicy_prototype$getDeviceCertRequestValues(),d={};a.logAvailableReplacements_();"Subject"in c&&(d.Subject=a.doReplacementsOnSubject_(c.Subject));
"SubjectAlternativeNames"in c&&c.SubjectAlternativeNames instanceof Array&&(d.SubjectAlternativeNames=a.doReplacementsOnSubjectAlternativeNames_(c.SubjectAlternativeNames));b.resolve(d)});return b.promise};O.$inject=["managedPolicyService","$q"];var Ea="CommonName Country DeviceSerialNumber Locality Organization OrganizationUnit State".split(" ");var P=function(a,b,c){this.managedPolicy=a;this.tokenService=b;this.ccr_services_RequestService$q=c;this.hasSpecificError=!1;this.ccr_services_RequestService$errorMessage=""};P.$inject=["managedPolicyService","tokenService","$q"];P.prototype.isSpecificErrorPresent=function(){return this.hasSpecificError};P.prototype.ccr_services_RequestService_prototype$getErrorMessage=function(){return this.ccr_services_RequestService$errorMessage};var Q=function(a,b,c){P.call(this,a,b,c);this.enrollmentUris_=[]};v(Q,P);t("ccr.services.CertificatePolicy",Q,void 0);Q.$inject=["managedPolicyService","tokenService","$q"];var R={RESPONSE:"response",CAS:"cAs",POLICY:"policy",CA_REFERENCE:"cAReference",COMMON_NAME:"commonName",CA_REFERENCE_ID:"cAReferenceID",CAURI:"cAURI",CLIENT_AUTHENTICATION:"clientAuthentication",RENEWAL_ONLY:"renewalOnly",URI:"uri"};
Q.prototype.contactPolicyServer=function(a,b){var c=this,d=c.ccr_services_RequestService$q.defer(),f=c.managedPolicy.getCepProxyUrl();L("Contacing CEP server at: "+f,K,c.managedPolicy.getLogLevel());var g=new XMLHttpRequest;g.open("POST",f,!0,a,b);g.withCredentials=!0;g.setRequestHeader("Content-type","application/soap+xml; charset=utf-8");g.onreadystatechange=function(){4==g.readyState&&(200==g.status?(c.cepSuccessCallback_(g.responseText),d.resolve()):(c.cepFailureCallback_(g.responseText,g.statusText),
d.reject()))};g.timeout=c.managedPolicy.getXhrRequestTimeout();g.ontimeout=function(){g.abort();c.hasSpecificError=!0;c.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("policy_timeout_error");L(c.ccr_services_RequestService$errorMessage,H,c.managedPolicy.getLogLevel());d.reject()};g.send('<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><s:Header><a:Action s:mustUnderstand="1">http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy/IPolicy/GetPolicies</a:Action><a:ReplyTo><a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">'+
f+'</a:To><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><o:UsernameToken u:Id="uuid-12df19ba-93db-4f41-8d7e-8bb789168bf9-1"><o:Username>'+a+"</o:Username><o:Password>"+b+'</o:Password></o:UsernameToken></o:Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"> <GetPolicies xmlns="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy"><client><lastUpdate>0001-01-01T00:00:00</lastUpdate><preferredLanguage xsi:nil="true"></preferredLanguage></client><requestFilter xsi:nil="true"></requestFilter></GetPolicies></s:Body></s:Envelope>');
return d.promise};Q.prototype.contactPolicyServer.$inject=["user","pass"];e=Q.prototype;e.cepSuccessCallback_=function(a){a=(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("GetPoliciesResponse")[0].childNodes;for(var b,c,d=0;d<a.length;d++)a[d].tagName==R.RESPONSE?b=a[d]:a[d].tagName==R.CAS&&(c=a[d]);this.enrollmentUris_=[];b&&c&&(b=this.mapAndFilterTemplateNamesAndCaRefs_(b),this.enrollmentUris_=this.getAvailableEndpointsFromCaTag_(c,b))};
e.mapAndFilterTemplateNamesAndCaRefs_=function(a){var b=this.tokenService.getMatchingTemplates(),c=a.getElementsByTagName(R.POLICY);a={};for(var d=0;d<c.length;d++){var f=c[d];a[f.getElementsByTagName(R.COMMON_NAME)[0].innerHTML]=f.getElementsByTagName(R.CA_REFERENCE)[0].innerHTML}c=[];for(d=0;d<b.length;d++)if(f=b[d],a[f]){var g={};g.name=f;g.ca=a[f];c.push(g)}return c};
e.getAvailableEndpointsFromCaTag_=function(a,b){var c=[];a=a.getElementsByTagName(R.CA_REFERENCE_ID);for(var d=0;d<b.length;d++)for(var f=b[d].ca,g=0;g<a.length;g++)if(a[g].innerHTML===f)for(var h=a[g].parentNode.getElementsByTagName(R.CAURI),p=0;p<h.length;p++){var q=h[p],n=q.getElementsByTagName(R.CLIENT_AUTHENTICATION);(n=n[n.length-1])&&"4"==n.innerHTML&&(n=q.getElementsByTagName(R.RENEWAL_ONLY),n=n[n.length-1],!n||"false"==n.innerHTML)&&(q=q.getElementsByTagName(R.URI),q=q[q.length-1])&&(q=q.innerHTML,
n={},n.name=b[d].name,n.uri=q,c.push(n))}return c};e.cepFailureCallback_=function(a,b){a=(new DOMParser).parseFromString(a,"text/xml");"FailedAuthentication"===M(a,"Value").slice(-20)?(this.hasSpecificError=!0,this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("invalid_credentials")):(this.hasSpecificError=!1,this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("policy_bad_response",b));L(this.ccr_services_RequestService$errorMessage,H,this.managedPolicy.getLogLevel())};
e.getAllEnrollmentUris=function(){return this.enrollmentUris_};var S=function(a,b,c,d){P.call(this,a,b,d);this.certRequestValuesService_=c;this.isCurrentRequestPending=this.hasEnrolledSuccessfully=!1;this.currentRequestUri=this.currentRequestId=this.currentCsr="";this.subjectAttributeMap_={};this.subjectAttributeMap_.CommonName="2.5.4.3";this.subjectAttributeMap_.Country="2.5.4.6";this.subjectAttributeMap_.DeviceSerialNumber="2.5.4.5";this.subjectAttributeMap_.Locality="2.5.4.7";this.subjectAttributeMap_.Organization="2.5.4.10";this.subjectAttributeMap_.OrganizationUnit=
"2.5.4.11";this.subjectAttributeMap_.State="2.5.4.8"};v(S,P);t("ccr.services.CertificateSaving",S,void 0);S.$inject=["managedPolicyService","tokenService","certRequestValuesService","$q"];var Fa={rfc822Name:1,dNSName:2,uniformResourceIdentifier:6};e=S.prototype;e.certHelper=function(a){return this.tokenService.getCurrentToken()?this.generateCsr_(a):null};
e.getAdditionalSubjectTypesAndValues=function(a){var b=[];if("system"!=this.tokenService.getCurrentTokenType())return b;if("Subject"in a){a=a.Subject;for(var c in this.subjectAttributeMap_)c in a&&b.push(new window.org.pkijs.simpl.ATTR_TYPE_AND_VALUE({type:this.subjectAttributeMap_[c],value:new window.org.pkijs.asn1.UTF8STRING({value:a[c]})}))}return b};e.makeValidIA5String=function(a){return a.replace(/[^\x00-\x7F]/g,"")};
e.getAdditionalExtensions=function(a){var b=[];if("system"!=this.tokenService.getCurrentTokenType())return b;if("SubjectAlternativeNames"in a){a=a.SubjectAlternativeNames;for(var c=[],d=0;d<a.length;++d){var f=a[d].NameType,g=a[d].Name;if(f in Fa){var h=Fa[f],p=this.makeValidIA5String(g);g!=p&&L("SAN value for NameType:"+f+" was not a valid IA5String - filtered",I,this.managedPolicy.getLogLevel());c.push(new window.org.pkijs.simpl.GENERAL_NAME({NameType:h,Name:p}))}else L("Skipping unsupport SAN NameType:"+
f,I,this.managedPolicy.getLogLevel())}0<c.length&&b.push(new window.org.pkijs.simpl.EXTENSION({extnID:"2.5.29.17",critical:!1,extnValue:(new window.org.pkijs.simpl.GENERAL_NAMES({names:c})).toSchema().toBER(!1)}))}return b};
e.generateCsr_=function(a){var b=this,c=this.ccr_services_RequestService$q.defer(),d=this.ccr_services_RequestService$q.defer(),f=d.promise;d.resolve();var g=new window.org.pkijs.simpl.PKCS10;g.version=0;g.attributes=[];var h=this.managedPolicy.getSignatureAlgorithm(),p,q,n=this.tokenService.getCurrentToken().subtleCrypto,Ga=window.crypto.subtle;window.org.pkijs.getCrypto=function(){return b.tokenService.getCurrentToken().subtleCrypto};var xa=!1;d=function(a){xa||(xa=!0,a&&(b.ccr_services_RequestService$errorMessage=
chrome.i18n.getMessage(a)),b.currentCsr="",c.reject());return c};f.then(function(){var a=window.org.pkijs.getAlgorithmParameters("RSASSA-PKCS1-V1_5","generatekey");"hash"in a.algorithm&&(a.algorithm.hash.name=h);return n.generateKey(a.algorithm,!1,a.usages)},d.bind(b,void 0)).then(function(a){p=a.publicKey;q=a.privateKey},d.bind(b,"saving_generate_key_failure")).then(function(){return g.subjectPublicKeyInfo.importKey(p)},d.bind(b,"saving_generate_extract_failure")).then(function(){return Ga.digest({name:"SHA-1"},
g.subjectPublicKeyInfo.subjectPublicKey.value_block.value_hex)},d.bind(b,"saving_generate_export_failure")).then(function(a){b.subjectPublicKeyDigestResult_=a;return b.certRequestValuesService_.module$contents$ccr$services$CertRequestValues_CertRequestValues_prototype$getDeviceCertRequestValues()},d.bind(b,"saving_generate_digest_failure")).then(function(c){var d=[];d.push(new window.org.pkijs.simpl.EXTENSION({extnID:"1.3.6.1.4.1.311.20.2",critical:!1,extnValue:(new window.org.pkijs.asn1.BMPSTRING({value:a})).toBER(!1)}));
d.push(new window.org.pkijs.simpl.EXTENSION({extnID:"2.5.29.14",critical:!1,extnValue:(new window.org.pkijs.asn1.OCTETSTRING({value_hex:b.subjectPublicKeyDigestResult_})).toBER(!1)}));Array.prototype.push.apply(d,b.getAdditionalExtensions(c));g.attributes.push(new window.org.pkijs.simpl.ATTRIBUTE({type:"1.2.840.113549.1.9.14",values:[(new window.org.pkijs.simpl.EXTENSIONS({extensions_array:d})).toSchema()]}));Array.prototype.push.apply(g.subject.types_and_values,b.getAdditionalSubjectTypesAndValues(c))},
d.bind(b,"saving_cert_request_values_failure")).then(function(){return g.sign(q,h)},d.bind(b,"saving_generate_push_failure")).then(function(){var a=g.toSchema().toBER(!1);b.currentCsr=window.btoa(Aa(a));c.resolve()},d.bind(b,"saving_generate_sign_failure"));return c.promise};
e.enroll=function(a,b,c,d){var f=this,g=f.ccr_services_RequestService$q.defer();if(0==d.length)return this.hasEnrolledSuccessfully=!1,this.hasSpecificError=!0,this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("login_no_uri_failure"),L(this.ccr_services_RequestService$errorMessage,H,this.managedPolicy.getLogLevel()),g.reject(),g.promise;d=f.certHelper(d[0]);if(null===d)return this.hasEnrolledSuccessfully=!1,g.reject(),g.promise;d.then(function(){if(""==f.currentCsr)f.hasEnrolledSuccessfully=
!1,L(f.ccr_services_RequestService$errorMessage,H,f.managedPolicy.getLogLevel()),g.reject();else{var d=new XMLHttpRequest;d.open("POST",a,!0,b,c);var p='<s:Envelope xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:s="http://www.w3.org/2003/05/soap-envelope"><s:Header><a:Action s:mustUnderstand="1">http://schemas.microsoft.com/windows/pki/2009/01/enrollment/RST/wstep</a:Action><a:ReplyTo><a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">'+
a+'</a:To><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><o:UsernameToken><o:Username>'+b+"</o:Username><o:Password>"+c+'</o:Password></o:UsernameToken></o:Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><RequestSecurityToken xmlns="http://docs.oasis-open.org/ws-sx/ws-trust/200512"><TokenType>http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3</TokenType><RequestType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue</RequestType><BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd#base64binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd#PKCS7" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">'+
f.currentCsr+'</BinarySecurityToken><RequestID xsi:nil="true" xmlns="http://schemas.microsoft.com/windows/pki/2009/01/enrollment" /></RequestSecurityToken></s:Body></s:Envelope>';d.withCredentials=!0;d.setRequestHeader("Content-type","application/soap+xml; charset=utf-8");d.onreadystatechange=function(){4==d.readyState&&(200==d.status?(f.enrollSuccessCallback(d.responseText),f.isEnrolledSuccessfully()||f.isRequestPending()?g.resolve():g.reject()):(f.enrollFailureCallback(d.responseText,d.statusText),
g.reject()))};d.timeout=f.managedPolicy.getXhrRequestTimeout();d.ontimeout=function(){d.abort();f.hasEnrolledSuccessfully=!1;f.hasSpecificError=!0;f.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_timeout_error");L(f.ccr_services_RequestService$errorMessage,H,f.managedPolicy.getLogLevel());g.reject()};d.send(p)}},function(){g.reject()});return g.promise};
e.checkPendingRequestStatus=function(a,b,c,d){var f=this,g=this.ccr_services_RequestService$q.defer();if(!f.tokenService.getCurrentToken())return f.hasEnrolledSuccessfully=!1,f.currentCsr="",g.reject(),g.promise;var h=new XMLHttpRequest;h.open("POST",a,!0,c,d);a='<s:Envelope xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:s="http://www.w3.org/2003/05/soap-envelope"><s:Header><a:Action s:mustUnderstand="1">http://schemas.microsoft.com/windows/pki/2009/01/enrollment/RST/wstep</a:Action><a:ReplyTo><a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address></a:ReplyTo><a:To s:mustUnderstand="1">'+
a+'</a:To><o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><o:UsernameToken><o:Username>'+c+"</o:Username><o:Password>"+d+'</o:Password></o:UsernameToken></o:Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><RequestSecurityToken xmlns="http://docs.oasis-open.org/ws-sx/ws-trust/200512"><TokenType>http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3</TokenType><RequestType>http://schemas.microsoft.com/windows/pki/2009/01/enrollment/QueryTokenStatus</RequestType><RequestID xmlns="http://schemas.microsoft.com/windows/pki/2009/01/enrollment">'+
b+"</RequestID></RequestSecurityToken></s:Body></s:Envelope>";h.withCredentials=!0;h.setRequestHeader("Content-type","application/soap+xml; charset=utf-8");h.onreadystatechange=function(){4==h.readyState&&(200==h.status?(f.enrollSuccessCallback(h.responseText),f.isEnrolledSuccessfully()||f.isRequestPending()?g.resolve():g.reject()):(f.enrollFailureCallback(h.responseText,h.statusText),g.reject()))};h.send(a);return g.promise};
e.enrollSuccessCallback=function(a){this.isCurrentRequestPending=this.hasEnrolledSuccessfully=!1;var b=(new DOMParser).parseFromString(a,"text/xml");a=M(b,"DispositionMessage");var c=a.slice(0,6);var d="";var f=b.getElementsByTagName("BinarySecurityToken");if(null!=f&&void 0!=f)for(var g=0;g<f.length;++g)if("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"==f[g].getAttribute("ValueType")){d=f[g].innerHTML;break}if(null==d||void 0==d)d="";f=M(b,"RequestID");g=
"";b=b.getElementsByTagName("Reference");null!=b&&void 0!=b&&0!=b.length&&(g=b[b.length-1].getAttribute("URI"));if(null==g||void 0==g)g="";b=g;""!=d&&"Issued"==c?this.storeCertificate(d)?this.hasEnrolledSuccessfully=!0:this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_store_failure"):"Taken Under Submission"==a?(this.isCurrentRequestPending=!0,this.currentRequestId=f,this.currentRequestUri=b,this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_pending",
[f,b])):this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_no_cert_failure")};
e.enrollFailureCallback=function(a,b){this.hasEnrolledSuccessfully=!1;a=(new DOMParser).parseFromString(a,"text/xml");var c=M(a,"Text"),d=c.slice(0,35);c=c.slice(0,6);"FailedAuthentication"===M(a,"Value").slice(-20)?(this.hasSpecificError=!0,this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("invalid_credentials")):"Denied by Policy Module  0x80094800"===d?(this.hasSpecificError=!0,this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_template_error")):"Denied"===
c?(this.hasSpecificError=!0,this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_denied")):(this.hasSpecificError=!1,this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_bad_response",b));L(this.ccr_services_RequestService$errorMessage,H,this.managedPolicy.getLogLevel())};
e.storeCertificate=function(a){L("Attempting to store a cert.",K,this.managedPolicy.getLogLevel());if(0<a.length){var b=Ba(window.atob(a));chrome.enterprise.platformKeys.importCertificate(this.tokenService.getCurrentToken().id,b);var c=this.managedPolicy.getHoursOffset();a=this.managedPolicy.getNotificationInterval();b=window.org.pkijs.fromBER(b);var d=new window.org.pkijs.simpl.CERT({schema:b.result});b=(new Uint8Array(d.serialNumber.value_block.value_hex)).toString();d=d.notAfter.value;Ca(b);var f=
d.getTime();0<c&&d.setHours(d.getHours()-c);for(c=0;d.getTime()<f;){var g={};g.name=b;g.num=c++;g=JSON.stringify(g);chrome.alarms.create(g,{when:d.getTime()});d.setHours(d.getHours()+a)}return!0}return!1};e.isEnrolledSuccessfully=function(){return this.hasEnrolledSuccessfully};e.isRequestPending=function(){return this.isCurrentRequestPending};e.getPendingRequestId=function(){return this.currentRequestId};e.getPendingRequestUri=function(){return this.currentRequestUri};var T=function(a,b,c,d,f,g){S.call(this,a,b,c,g);this.ccr_services_EnrollmentAgent$http_=f;this.verifiedAccessService_=d;this.chromeIdentityEmail_=""};v(T,S);t("ccr.services.EnrollmentAgent",T,void 0);T.$inject="managedPolicyService tokenService certRequestValuesService verifiedAccessService $http $q".split(" ");e=T.prototype;
e.enroll=function(a,b,c,d){var f=this,g=f.ccr_services_RequestService$q.defer(),h=f.certHelper(d[0]);if(null===h)return g.reject(),g.promise;h.then(function(){""==f.currentCsr?(f.hasEnrolledSuccessfully=!1,L(f.ccr_services_RequestService$errorMessage,H,f.managedPolicy.getLogLevel()),g.reject()):f.verifiedAccessService_.makeCsrToken().then(function(){var h=f.verifiedAccessService_.getCsrToken();""==h?(f.setErrorBasedOnVerifiedAccess_(),g.reject()):f.setChromeIdentityEmail_().then(function(){f.postEnrollmentRequest_(a,
b,c,d,h).then(function(){f.isEnrolledSuccessfully()||f.isRequestPending()?g.resolve():g.reject()},function(){g.reject()})},function(){g.reject()})},function(){f.setErrorBasedOnVerifiedAccess_();g.reject()})},function(){g.reject()});return g.promise};
e.postEnrollmentRequest_=function(a,b,c,d,f){var g=this;return g.ccr_services_EnrollmentAgent$http_.post(a,{adUsername:b,adPassword:c,templates:d,csrToken:f,expectedIdentity:this.chromeIdentityEmail_,vaSharedSecret:this.managedPolicy.getVerifiedAccessSharedSecret(),pkcsCsr:this.currentCsr,csrType:"pkcs10",shouldEnrollForMachine:this.tokenService.isCurrentTokenSystemType()},{withCredentials:!0,timeout:this.managedPolicy.getVerifiedAccessRequestTimeout(),headers:{"Content-Type":"application/json; charset=utf-8"}}).then(function(a){g.enrollSuccessCallback(a.data.certificate)},
function(a){-1===a.status?g.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("cea_timed_out"):(a=a.data.error,g.isKeyForValidMessage_(a)?g.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage(a):g.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("cea_error_other"));g.hasSpecificError=!0;g.hasEnrolledSuccessfully=!1})};
e.enrollSuccessCallback=function(a){this.isCurrentRequestPending=this.hasEnrolledSuccessfully=!1;""==a?this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_no_cert_failure"):(this.hasEnrolledSuccessfully=a=this.storeCertificate(a),a||(this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("saving_store_failure")))};
e.setErrorBasedOnVerifiedAccess_=function(){this.hasEnrolledSuccessfully=!1;this.hasSpecificError=this.verifiedAccessService_.isSpecificErrorPresent();this.ccr_services_RequestService$errorMessage=this.verifiedAccessService_.ccr_services_RequestService_prototype$getErrorMessage();L(this.ccr_services_RequestService$errorMessage,H,this.managedPolicy.getLogLevel())};e.isKeyForValidMessage_=function(a){return""!=chrome.i18n.getMessage(a)};
e.setChromeIdentityEmail_=function(){var a=this,b=this.ccr_services_RequestService$q.defer(),c=b.promise;chrome.identity.getProfileUserInfo(function(c){a.chromeIdentityEmail_=c.email;b.resolve()});return c};var V=function(a){this.cepProxyUrl_="";this.isMachineCertEnrollmentAllowed_=this.isAutoEnrollmentEnabled_=!1;this.userEnrollmentTemplates_=["ChromeOSWirelessUser"];this.deviceEnrollmentTemplates_=["ChromeOSWirelessDevice"];this.deviceCertRequestValues_={};this.placeholderValues_={Username:"Username",Password:"Password",Uri:"Enrollment URI",RequestId:"Request ID",Header:"Certificate Enrollment"};this.companyInfo_={name:"Your company name goes here.",logo:"Your company logo goes here.",help_url:"https://support.google.com/chrome/a/answer/6324985",
help_text:"Please contact your administrator for assistance."};this.logLevel_=0;this.signatureAlgo_=U.SHA512;this.isPendingUIEnabled_=!1;this.renewHoursBeforeExpiry_=120;this.renewReminderInterval_=24;this.requestTimeoutMilliseconds_=2E4;this.apiKey_="";this.isVerifiedAccessEnabled_=!1;this.verifiedAccessUrl_="https://verifiedaccess.googleapis.com/v1/challenge?key=";this.verifiedAccessSharedSecret_="";this.vaRequestTimeoutMilliseconds_=6E4;this.ccr_services_ManagedPolicy$q_=a};
t("ccr.services.ManagedPolicy",V,void 0);V.$inject=["$q"];var U={SHA1:"SHA-1",SHA256:"SHA-256",SHA512:"SHA-512"};e=V.prototype;e.getLoginPageLoginTabLabel=function(){return chrome.i18n.getMessage("managed_login_tab_label")};e.getLoginPageStatusTabLabel=function(){return chrome.i18n.getMessage("managed_status_tab_label")};e.getLoginPageDeviceWideCheckboxText=function(){return chrome.i18n.getMessage("managed_login_checkbox")};e.getLoginPageLoginButtonText=function(){return chrome.i18n.getMessage("managed_login_button")};
e.getLoginPageStatusHeaderText=function(){return chrome.i18n.getMessage("managed_status_header")};e.getLoginPageStatusButtonText=function(){return chrome.i18n.getMessage("managed_status_button")};e.getLoginPageMoreOptionsText=function(){return chrome.i18n.getMessage("managed_more_options")};e.getLoginPageHelpLabelText=function(){return chrome.i18n.getMessage("managed_help_text")};e.getLoginPageLicenseButtonText=function(){return chrome.i18n.getMessage("managed_license_button")};
e.getLoginPageClipboardButtonText=function(){return chrome.i18n.getMessage("managed_clipboard_button")};e.getCompanyName=function(){return this.companyInfo_&&this.companyInfo_.name?this.companyInfo_.name:"Your company name goes here."};e.getCompanyLogo=function(){return this.companyInfo_&&this.companyInfo_.logo?this.companyInfo_.logo:"Your company logo goes here."};e.getHelpUrl=function(){return this.companyInfo_&&this.companyInfo_.help_url?this.companyInfo_.help_url:"https://support.google.com/chrome/a/answer/6324985"};
e.getHelpText=function(){return this.companyInfo_&&this.companyInfo_.help_text?this.companyInfo_.help_text:""};e.getLoginPageHeaderText=function(){return this.placeholderValues_&&this.placeholderValues_.Header?"managed_login_header"==this.placeholderValues_.Header?chrome.i18n.getMessage("managed_login_header"):this.placeholderValues_.Header:"Certificate Enrollment"};
e.getUsernameFormFieldPlaceholder=function(){return this.placeholderValues_&&this.placeholderValues_.Username?"managed_username_placeholder"==this.placeholderValues_.Username?chrome.i18n.getMessage("managed_username_placeholder"):this.placeholderValues_.Username:"Username"};
e.getPasswordFormFieldPlaceholder=function(){return this.placeholderValues_&&this.placeholderValues_.Password?"managed_password_placeholder"==this.placeholderValues_.Password?chrome.i18n.getMessage("managed_password_placeholder"):this.placeholderValues_.Password:"Password"};e.getUriFormFieldPlaceholder=function(){return this.placeholderValues_&&this.placeholderValues_.Uri?this.placeholderValues_.Uri:"Enrollment URI"};
e.getRequestIdFormFieldPlaceholder=function(){return this.placeholderValues_&&this.placeholderValues_.RequestId?this.placeholderValues_.RequestId:"Request ID"};e.getCepProxyUrl=function(){return this.cepProxyUrl_};e.isMachineCertEnrollmentAllowed=function(){return this.isMachineCertEnrollmentAllowed_};e.getUserEnrollmentTemplates=function(){return this.userEnrollmentTemplates_};e.getDeviceEnrollmentTemplates=function(){return this.deviceEnrollmentTemplates_};e.getLogLevel=function(){return this.logLevel_};
e.getSignatureAlgorithm=function(){return this.signatureAlgo_};e.isPendingUIEnabled=function(){return this.isPendingUIEnabled_};e.getHoursOffset=function(){return this.renewHoursBeforeExpiry_};e.getNotificationInterval=function(){return this.renewReminderInterval_};e.getXhrRequestTimeout=function(){return 0<this.requestTimeoutMilliseconds_?this.requestTimeoutMilliseconds_:2E4};e.getApiKey=function(){return this.apiKey_};e.isVerifiedAccessEnabled=function(){return this.isVerifiedAccessEnabled_};
e.getVerifiedAccessUrl=function(){return""!=this.verifiedAccessUrl_?this.verifiedAccessUrl_:"https://verifiedaccess.googleapis.com/v1/challenge?key="};e.getVerifiedAccessSharedSecret=function(){return this.verifiedAccessSharedSecret_};e.getVerifiedAccessRequestTimeout=function(){return 0<this.vaRequestTimeoutMilliseconds_?this.vaRequestTimeoutMilliseconds_:6E4};e.setCepProxyUrl_=function(a){this.cepProxyUrl_=a};e.setAutoEnrollmentEnabled_=function(a){this.isAutoEnrollmentEnabled_=a};
e.setMachineCertEnrollmentAllowed_=function(a){this.isMachineCertEnrollmentAllowed_=a};e.setUserEnrollmentTemplates_=function(a){this.userEnrollmentTemplates_=a};e.setDeviceEnrollmentTemplates_=function(a){this.deviceEnrollmentTemplates_=a};e.setDeviceCertRequestValues_=function(a){this.deviceCertRequestValues_=a};e.ccr_services_ManagedPolicy_prototype$getDeviceCertRequestValues=function(){return this.deviceCertRequestValues_};e.setPlaceholderValues_=function(a){this.placeholderValues_=a};
e.setCompanyInfo_=function(a){this.companyInfo_=a};e.setLogLevel_=function(a){a=G.indexOf(a);-1!=a?this.logLevel_=a:L(chrome.i18n.getMessage("managed_log_level_error"),H,this.getLogLevel())};e.setSignatureAlgorithm_=function(a){U[a]?this.signatureAlgo_=U[a]:L(chrome.i18n.getMessage("managed_signature_algo_error"),H,this.getLogLevel())};e.setPendingUIEnabled_=function(a){this.isPendingUIEnabled_=a};e.setRenewHoursBeforeExpiry_=function(a){this.renewHoursBeforeExpiry_=a};
e.setRenewReminderInterval_=function(a){this.renewReminderInterval_=a};e.setXhrRequestTimeoutMilliseconds_=function(a){this.requestTimeoutMilliseconds_=1E3*a};e.setApiKey_=function(a){this.apiKey_=a};e.setVerifiedAccessEnabled_=function(a){this.isVerifiedAccessEnabled_=a};e.setVerifiedAccessUrl_=function(a){this.verifiedAccessUrl_=a};e.setVerifiedAccessSharedSecret_=function(a){this.verifiedAccessSharedSecret_=a};
e.setVaRequestTimeoutMilliseconds_=function(a){this.vaRequestTimeoutMilliseconds_=1E3*a};
e.populatePolicyChanges_=function(a){L(chrome.i18n.getMessage("managed_policy_handling_info"),J,this.getLogLevel());a=JSON.parse(a);for(var b in a){var c=a[b];switch(b){case "cep_proxy_url":this.setCepProxyUrl_(c);break;case "enable_auto_enrollment":this.setAutoEnrollmentEnabled_(c);break;case "allow_machine_cert_enrollment":this.setMachineCertEnrollmentAllowed_(c);break;case "user_enrollment_templates":this.setUserEnrollmentTemplates_(c);break;case "device_enrollment_templates":this.setDeviceEnrollmentTemplates_(c);
break;case "device_cert_request_values":this.setDeviceCertRequestValues_(c);break;case "placeholder_values":this.setPlaceholderValues_(c);break;case "company_info":this.setCompanyInfo_(c);break;case "log_level":this.setLogLevel_(c);break;case "signature_algo":this.setSignatureAlgorithm_(c);break;case "pending_ui_enabled":this.setPendingUIEnabled_(c);break;case "renew_hours_before_expiry":this.setRenewHoursBeforeExpiry_(c);break;case "renew_reminder_interval":this.setRenewReminderInterval_(c);break;
case "request_timeout_seconds":this.setXhrRequestTimeoutMilliseconds_(c);break;case "va_api_key":this.setApiKey_(c);break;case "va_enabled":this.setVerifiedAccessEnabled_(c);break;case "va_google_url":this.setVerifiedAccessUrl_(c);break;case "va_shared_secret":this.setVerifiedAccessSharedSecret_(c);break;case "va_request_timeout_seconds":this.setVaRequestTimeoutMilliseconds_(c)}}b=this.getCepProxyUrl();""===b?L(chrome.i18n.getMessage("managed_cep_empty_error"),H,this.getLogLevel()):this.isHttpsUrl_(b)||
L(chrome.i18n.getMessage("managed_cep_http_error"),H,this.getLogLevel());this.isHttpsUrl_(this.getVerifiedAccessUrl())||L(chrome.i18n.getMessage("managed_va_url_http_error"),H,this.getLogLevel());this.isHttpsUrl_(this.getHelpUrl())||L(chrome.i18n.getMessage("managed_company_url_http_error"),H,this.getLogLevel())};
e.requestPolicyUpdate=function(){var a=this,b=a.ccr_services_ManagedPolicy$q_.defer();L(chrome.i18n.getMessage("managed_policy_request_info"),J,K);chrome.runtime.sendMessage({action:"policyRequest"},function(c){L(chrome.i18n.getMessage("managed_policy_response_info"),J,K);"{}"===c||void 0===c?a.getPolicyUpdateDirectly_():a.populatePolicyChanges_(c);b.resolve()});return b.promise};
e.getPolicyUpdateDirectly_=function(){var a=this;chrome.storage.managed.get(function(b){if(0==Object.keys(b).length)L("No managed policy found. Consumer mode.",J,K);else{L("Managed policy found. Enterprise mode.",J,K);var c={},d;for(d in b){var f=b[d];ya[d]?c[d]=f:(f=chrome.i18n.getMessage("invalid_policy_var",[d,f.toString()]),L(f,I,K))}b=JSON.stringify(c);a.populatePolicyChanges_(b);chrome.runtime.sendMessage({action:"policyStore",data:b},function(){})}})};
e.isHttpsUrl_=function(a){return"https://"!==a.toLowerCase().slice(0,8)?!1:8<a.length};var W=function(a,b){this.ccr_services_Token$managedPolicy_=a;this.ccr_services_Token$q_=b;this.currentToken_=void 0;this.errorMessage_=this.tokenType_=""};t("ccr.services.Token",W,void 0);W.$inject=["managedPolicyService","$q"];var X={USER:"user",SYSTEM:"system"};e=W.prototype;
e.setTokenFromPlatformKeys=function(a){var b=this,c=b.ccr_services_Token$q_.defer();void 0!=chrome.enterprise&&void 0!=chrome.enterprise.platformKeys?chrome.enterprise.platformKeys.getTokens(function(d){for(var f=void 0,g=void 0,h=0;h<d.length;h++)switch(d[h].id){case "user":f=d[h];break;case "system":g=d[h]}a?b.ccr_services_Token$managedPolicy_.isMachineCertEnrollmentAllowed()?void 0!=g?(b.currentToken_=g,b.tokenType_=X.SYSTEM,c.resolve()):(b.errorMessage_=chrome.i18n.getMessage("token_no_system_failure"),
b.currentToken_=void 0,b.tokenType_="",c.reject()):(b.errorMessage_=chrome.i18n.getMessage("token_system_unallowed_failure"),b.currentToken_=void 0,b.tokenType_="",c.reject()):void 0!=f?(b.currentToken_=f,b.tokenType_=X.USER,c.resolve()):(b.errorMessage_=chrome.i18n.getMessage("token_no_user_failure"),b.currentToken_=void 0,b.tokenType_="",c.reject())}):(b.errorMessage_=chrome.i18n.getMessage("token_no_user_failure"),b.currentToken_=void 0,b.tokenType_="",c.reject());return c.promise};
e.getCurrentToken=function(){return this.currentToken_};e.getCurrentTokenType=function(){return this.tokenType_};e.ccr_services_Token_prototype$getErrorMessage=function(){return this.errorMessage_};e.getMatchingTemplates=function(){return this.tokenType_===X.USER?this.ccr_services_Token$managedPolicy_.getUserEnrollmentTemplates():this.tokenType_===X.SYSTEM?this.ccr_services_Token$managedPolicy_.getDeviceEnrollmentTemplates():[]};e.isCurrentTokenSystemType=function(){return this.tokenType_===X.SYSTEM};var Y=function(a,b,c,d,f){P.call(this,a,b,f);this.ccr_services_VerifiedAccess$http_=c;this.csrToken_="";this.rawChallenge_={challenge:{data:"",signature:""}};this.encodedChallenge_=""};v(Y,P);t("ccr.services.VerifiedAccess",Y,void 0);Y.$inject=["managedPolicyService","tokenService","$http","$timeout","$q"];e=Y.prototype;e.getCsrToken=function(){return this.csrToken_};
e.makeCsrToken=function(){var a=this,b=a.ccr_services_RequestService$q.defer();a.getChallengeFromEndpoint_().then(function(){a.encodedChallenge_=a.encodeChallenge_(a.rawChallenge_);a.generateChallengeResponse_(a.encodedChallenge_).then(function(){b.resolve()},function(){""==a.ccr_services_RequestService$errorMessage&&(a.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("generate_challenge_response_failed"));b.reject()})},function(){""==a.ccr_services_RequestService$errorMessage&&(a.ccr_services_RequestService$errorMessage=
chrome.i18n.getMessage("get_challenge_failed"));b.reject()});return b.promise};
e.getChallengeFromEndpoint_=function(){var a=this,b=a.managedPolicy.getApiKey(),c=a.managedPolicy.getVerifiedAccessUrl();if("https"!==c.slice(0,5)||""==b)return c=a.ccr_services_RequestService$q.defer(),b=c.promise,c.reject(),b;b=c+b;c={"Content-Type":"application/json; charset=utf-8","User-Agent":"CCRVA-"+chrome.app.getDetails().version+"-"+c};return b=a.ccr_services_VerifiedAccess$http_.post(b,{},{withCredentials:!0,timeout:a.managedPolicy.getVerifiedAccessRequestTimeout(),headers:c}).then(function(b){a.rawChallenge_=
b.data},function(b){a.ccr_services_RequestService$errorMessage=-1===b.status?chrome.i18n.getMessage("get_challenge_timed_out"):chrome.i18n.getMessage("get_challenge_failed");a.rawChallenge_={challenge:{data:"",signature:""}}})};
e.generateChallengeResponse_=function(a){var b=this,c=b.ccr_services_RequestService$q.defer(),d=c.promise;a=window.atob(a);a=Ba(a);try{if(void 0!=chrome.enterprise&&void 0!=chrome.enterprise.platformKeys){var f=function(a){a=Aa(a);b.csrToken_=window.btoa(a);c.resolve()};this.tokenService.isCurrentTokenSystemType()?chrome.enterprise.platformKeys.challengeMachineKey(a,f):chrome.enterprise.platformKeys.challengeUserKey(a,!0,f)}else this.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("cea_no_api_failure"),
L(this.ccr_services_RequestService$errorMessage,H,this.managedPolicy.getLogLevel()),c.reject()}catch(g){b.ccr_services_RequestService$errorMessage=chrome.i18n.getMessage("generate_challenge_response_failed"),L(b.ccr_services_RequestService$errorMessage,H,b.managedPolicy.getLogLevel()),L(g.message,H,b.managedPolicy.getLogLevel()),c.reject()}return d};e.setSpecificError_=function(a){this.ccr_services_RequestService$errorMessage=a;this.hasSpecificError=!0};
e.encodeChallenge_=function(a){a=this.protoEncodeChallenge_(window.atob(a.challenge.data),window.atob(a.challenge.signature));return window.btoa(a)};e.protoEncodeChallenge_=function(a,b){var c="\n"+this.varintEncode_(a.length);c=c+a+"\u0012"+this.varintEncode_(b.length);return c+=b};e.varintEncode_=function(a){return 127>=a?String.fromCharCode(a):String.fromCharCode(128+(a&127),a>>>7)};var Z=angular.module("ccrApp.services",[]);Z.service("managedPolicyService",V);Z.service("requestService",P);Z.service("certificatePolicyService",Q);Z.service("certificateSavingService",S);Z.service("tokenService",W);Z.service("verifiedAccessService",Y);Z.service("enrollmentAgentService",T);Z.service("certRequestValuesService",O);angular.module("ccrApp.directives",[]);angular.module("ccrApp.controllers",["ngRoute","ngSanitize","ccrApp.services"]).controller("ccr.controllers.LoginPageCtrl",N);
angular.module("ccrApp",["ngMaterial","ccrApp.services","ccrApp.directives","ccrApp.controllers"]);angular.element(document.getElementById("angular-bootstrap")).ready(function(){var a=document.getElementById("angular-bootstrap");a&&angular.bootstrap(a,["ccrApp"])});
