var MODULESETS = {}; var ROW_KEYS = {}; var ROW_KEY_SIGNATURES = {};
MODULESETS['background_script.js'] = 'background'; ROW_KEYS['background'] = 'classroom-live.background.en_US.nhuU7z8NCL0.OL';
MODULESETS['inject_script.js'] = 'inject'; ROW_KEYS['inject'] = 'classroom-live.inject.en_US.xriV1CXnofA.OL';
MODULESETS['options_script.js'] = 'options'; ROW_KEYS['options'] = 'classroom-live.options.en_US.LuiABgAcAOg.OL';
MODULESETS['popup_script.js'] = 'popup'; ROW_KEYS['popup'] = 'classroom-live.popup.en_US.UK5ys52jGHY.OL';
/* _GlobalPrefix_ */
/* _Module_:inject */
try{
var k,_DumpException=function(a){throw a;};var l=this,m=function(a){return void 0!==a},n=function(a){return"string"==typeof a},aa=function(){},ba=function(a){a.O=void 0;a.I=function(){return a.O?a.O:a.O=new a}},ca=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";
if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},da=function(a){var b=ca(a);return"array"==b||"object"==b&&"number"==typeof a.length},p=function(a){return"function"==ca(a)},q=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ea="closure_uid_"+(1E9*Math.random()>>>0),fa=0,ha=function(a,b,c){return a.call.apply(a.bind,
arguments)},ia=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},r=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?r=ha:r=ia;return r.apply(null,arguments)},ja=Date.now||function(){return+new Date},t=function(a,b){function c(){} c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ta=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
var u=l.JSON.stringify;var v=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,v);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};t(v,Error);v.prototype.name="CustomError";var ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},sa=function(a){if(!la.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(pa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(qa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ra,"&#0;"));return a},ma=/&/g,na=/</g,oa=/>/g,pa=/"/g,qa=/'/g,ra=/\x00/g,la=/[\x00&<>"']/, ta=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)},ua=function(a,b){return a<b?-1:a>b?1:0};
var va=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(n(a))return n(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},w=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},wa=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,
b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0},za=function(a){var b=xa;a=ya(b,a,void 0);return 0>a?null:n(b)?b.charAt(a):b[a]},ya=function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1},Aa=function(a,b){0<=va(a,b)||a.push(b)},Ba=function(a,b){b=va(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},Ca=function(a){return Array.prototype.concat.apply([],
arguments)},Da=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Fa=function(a,b,c,d){Array.prototype.splice.apply(a,Ea(arguments,1))},Ea=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};
var x;a:{var Ga=l.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){x=Ha;break a}}x=""}var y=function(a){return-1!=x.indexOf(a)};var Ia=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ja=function(a){var b=0,c;for(c in a)b++;return b},Ka=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},La=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Ma=function(a,b){return null!==a&&b in a},Na="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Oa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Na.length;f++)c= Na[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Qa=function(a,b){var c=Pa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ra=y("Opera"),z=y("Trident")||y("MSIE"),Sa=y("Edge"),Ta=y("Gecko")&&!(-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),Ua=-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"),Va=function(){var a=l.document;return a?a.documentMode:void 0},Wa;
a:{var Xa="",Ya=function(){var a=x;if(Ta)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Sa)return/Edge\/([\d\.]+)/.exec(a);if(z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ua)return/WebKit\/(\S+)/.exec(a);if(Ra)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ya&&(Xa=Ya?Ya[1]:"");if(z){var Za=Va();if(null!=Za&&Za>parseFloat(Xa)){Wa=String(Za);break a}}Wa=Xa}
var $a=Wa,Pa={},A=function(a){return Qa(a,function(){for(var b=0,c=ka(String($a)).split("."),d=ka(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=ua(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||ua(0==g[2].length,0==h[2].length)||ua(g[2],h[2]);g=g[3];h=h[3]}while(0==b)}return 0<=b})},ab;var bb=l.document; ab=bb&&z?Va()||("CSS1Compat"==bb.compatMode?parseInt($a,10):5):void 0;
var cb=function(a,b,c,d,e){this.reset(a,b,c,d,e)};cb.prototype.g=0;cb.prototype.a=null;var db=0;cb.prototype.reset=function(a,b,c,d,e){this.g="number"==typeof e?e:db++;this.l=d||ja();this.b=a;this.h=b;this.c=c;delete this.a};cb.prototype.getMessage=function(){return this.h};
var eb=function(a){this.h=a;this.a=this.g=this.b=this.c=null},B=function(a,b){this.name=a;this.value=b};B.prototype.toString=function(){return this.name};var fb=new B("WARNING",900),gb=new B("INFO",800),hb=new B("CONFIG",700),ib=new B("FINE",500),xa=[new B("OFF",Infinity),new B("SHOUT",1200),new B("SEVERE",1E3),fb,gb,hb,ib,new B("FINER",400),new B("FINEST",300),new B("ALL",0)],jb=function(a,b){a.a||(a.a=[]);a.a.push(b)};eb.prototype.getChildren=function(){this.g||(this.g={});return this.g};
var kb=function(a,b){a.b=b},lb=function(a){return a.b?a.b:a.c?lb(a.c):null};eb.prototype.log=function(a,b,c){if(a.value>=lb(this).value)for(p(b)&&(b=b()),a=new cb(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),(b=l.console)&&b.timeStamp&&b.timeStamp(c),(b=l.msWriteProfilerMark)&&b(c),c=this;c;){var d=c,e=a;if(d.a)for(var f=0;b=d.a[f];f++)b(e);c=c.c}};
var mb={},nb=null,ob=function(){nb||(nb=new eb(""),mb[""]=nb,nb.b=hb)},pb=function(){ob();return nb},qb=function(a){ob();var b;if(!(b=mb[a])){b=new eb(a);var c=a.lastIndexOf("."),d=a.substr(c+1);c=qb(a.substr(0,c));c.getChildren()[d]=b;b.c=c;mb[a]=b}return b};
var C=function(a,b){a&&a.log(fb,b,void 0)},rb=function(a,b){a&&a.log(ib,b,void 0)};var sb=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("[goog.string.format] Template required");return d.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,h,F,G,hd,id){if("%"==G)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("[goog.string.format] Not enough arguments");arguments[0]=e;return D[G].apply(null,arguments)})},D={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?
a+ta(" ",Number(c)-a.length):ta(" ",Number(c)-a.length)+a},f:function(a,b,c,d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+ta(" ",a):f+ta(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,g,h){return D.f(parseInt(a, 10),b,c,d,0,f,g,h)}};D.i=D.d;D.u=D.d;
var E=function(a,b,c,d){v.call(this,a);this.details=b?n(b)?b:b.message:void 0;this.helpText=c;this.errorType=d;a=l.MODULESETS;Ja(a)&&(a=sb("chrome-extension://%s/(%s):(\\d+):(\\d+)",chrome.runtime.id,La(a).join("|")),this.stack=this.stack.replace(new RegExp(a,"g"),tb));a=qb("edulive.errors.Error");rb(a,this.toString())};t(E,v);E.prototype.toJSON=function(){var a={};Object.getOwnPropertyNames(this).forEach(function(b){a[b]=this[b]},this);return a};E.prototype.name="edulive.errors.Error";
var tb=function(a,b,c,d){var e=l.MODULESETS;b=e[b];if(!b)return a;a=l.ROW_KEYS[b];var f=l.ROW_KEY_SIGNATURES[b];c-=Ja(e)+1;return f?sb("https://www.gstatic.com/classroom-live/_/js/k=%s/m=%s/rt=j/d=1/rs=%s:%d:%d",a,b,f,c,d):sb("https://www.gstatic.com/classroom-live/_/js/k=%s/m=%s/rt=j/d=1:%d:%d",a,b,c,d)},vb=function(a){E.call(this,"");w(Ka(ub),function(b){b in a&&(this[b]=a[b])},this)};t(vb,E);vb.prototype.name="edulive.errors.SerializedError"; var ub={ia:"columnNumber",ja:"details",ka:"errorType",la:"fileName",ma:"helpText",na:"lineNumber",oa:"message",pa:"name",qa:"stack",ra:"status",sa:"type"};
var wb="StopIteration"in l?l.StopIteration:{message:"StopIteration",stack:""},xb=function(){};xb.prototype.next=function(){throw wb;};xb.prototype.L=function(){return this};var H=function(a,b){this.b={};this.a=[];this.g=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof H?(c=a.F(),d=a.w()):(c=La(a),d=Ka(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};H.prototype.w=function(){yb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};H.prototype.F=function(){yb(this);return this.a.concat()};
H.prototype.clear=function(){this.b={};this.g=this.c=this.a.length=0};H.prototype.remove=function(a){return I(this.b,a)?(delete this.b[a],this.c--,this.g++,this.a.length>2*this.c&&yb(this),!0):!1};var yb=function(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];I(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],I(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};H.prototype.get=function(a,b){return I(this.b,a)?this.b[a]:b};
H.prototype.set=function(a,b){I(this.b,a)||(this.c++,this.a.push(a),this.g++);this.b[a]=b};H.prototype.forEach=function(a,b){for(var c=this.F(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};H.prototype.L=function(a){yb(this);var b=0,c=this.g,d=this,e=new xb;e.next=function(){if(c!=d.g)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw wb;var e=d.a[b++];return a?e:d.b[e]};return e}; var I=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var zb=function(a){if(a.w&&"function"==typeof a.w)return a.w();if(n(a))return a.split("");if(da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ka(a)};var Ab=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,Bb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};
var J=function(a,b){this.b=this.j=this.c="";this.o=null;this.g=this.a="";this.h=!1;var c;a instanceof J?(this.h=m(b)?b:a.h,Cb(this,a.c),this.j=a.j,this.b=a.b,Db(this,a.o),this.a=a.a,Eb(this,Fb(a.l)),this.g=a.g):a&&(c=String(a).match(Ab))?(this.h=!!b,Cb(this,c[1]||"",!0),this.j=Gb(c[2]||""),this.b=Gb(c[3]||"",!0),Db(this,c[4]),this.a=Gb(c[5]||"",!0),Eb(this,c[6]||"",!0),this.g=Gb(c[7]||"")):(this.h=!!b,this.l=new K(null,0,this.h))};
J.prototype.toString=function(){var a=[],b=this.c;b&&a.push(Hb(b,Ib,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Hb(b,Ib,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.o,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Hb(c,"/"==c.charAt(0)?Jb:Kb,!0));(c=this.l.toString())&&a.push("?",c);(c=this.g)&&a.push("#",Hb(c,Lb));return a.join("")};
var Cb=function(a,b,c){a.c=c?Gb(b,!0):b;a.c&&(a.c=a.c.replace(/:$/,""))},Db=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null},Eb=function(a,b,c){b instanceof K?(a.l=b,Mb(a.l,a.h)):(c||(b=Hb(b,Nb)),a.l=new K(b,0,a.h))},Ob=function(a){return a instanceof J?new J(a):new J(a,void 0)},Pb=function(){var a=L;if(".."==a||"."==a)return"";if(-1!=a.indexOf("./")||-1!=a.indexOf("/.")){var b=0==a.lastIndexOf("/",0);a=a.split("/");for(var c=[],d=0;d<a.length;){var e=
a[d++];"."==e?b&&d==a.length&&c.push(""):".."==e?((1<c.length||1==c.length&&""!=c[0])&&c.pop(),b&&d==a.length&&c.push("")):(c.push(e),b=!0)}return c.join("/")}return a},Gb=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Hb=function(a,b,c){return n(a)?(a=encodeURI(a).replace(b,Qb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Qb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ib=/[#\/\?@]/g,Kb=/[\#\?:]/g,Jb=/[\#\?]/g,
Nb=/[\#\?@]/g,Lb=/#/g,K=function(a,b,c){this.b=this.a=null;this.c=a||null;this.g=!!c},M=function(a){a.a||(a.a=new H,a.b=0,a.c&&Bb(a.c,function(b,c){b=decodeURIComponent(b.replace(/\+/g," "));M(a);a.c=null;b=N(a,b);var d=a.a.get(b);d||a.a.set(b,d=[]);d.push(c);a.b+=1}))};K.prototype.remove=function(a){M(this);a=N(this,a);return I(this.a.b,a)?(this.c=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};K.prototype.clear=function(){this.a=this.c=null;this.b=0};
var Rb=function(a,b){M(a);b=N(a,b);return I(a.a.b,b)};k=K.prototype;k.forEach=function(a,b){M(this);this.a.forEach(function(c,d){w(c,function(c){a.call(b,c,d,this)},this)},this)};k.F=function(){M(this);for(var a=this.a.w(),b=this.a.F(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};k.w=function(a){M(this);var b=[];if(n(a))Rb(this,a)&&(b=Ca(b,this.a.get(N(this,a))));else{a=this.a.w();for(var c=0;c<a.length;c++)b=Ca(b,a[c])}return b};
k.set=function(a,b){M(this);this.c=null;a=N(this,a);Rb(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};k.get=function(a,b){a=a?this.w(a):[];return 0<a.length?String(a[0]):b};k.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.F(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.w(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.c=a.join("&")};
var Fb=function(a){var b=new K;b.c=a.c;a.a&&(b.a=new H(a.a),b.b=a.b);return b},N=function(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b},Mb=function(a,b){b&&!a.g&&(M(a),a.c=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),this.remove(c),0<a.length&&(this.c=null,this.a.set(N(this,c),Da(a)),this.b+=a.length))},a));a.g=b};
var Sb=Ob("https://classroomlive-pa.googleapis.com"),O=Ob("/v2/"),P=new J(Sb),Q=!!O.c;Q?Cb(P,O.c):Q=!!O.j;Q?P.j=O.j:Q=!!O.b;Q?P.b=O.b:Q=null!=O.o;var L=O.a;if(Q)Db(P,O.o);else if(Q=!!O.a){if("/"!=L.charAt(0))if(Sb.b&&!Sb.a)L="/"+L;else{var Tb=P.a.lastIndexOf("/");-1!=Tb&&(L=P.a.substr(0,Tb+1)+L)}L=Pb()}Q?P.a=L:Q=""!==O.l.toString();Q?Eb(P,Fb(O.l)):Q=!!O.g;Q&&(P.g=O.g);
var R=chrome.i18n.getMessage("2050089326602918210");chrome.i18n.getMessage("4849976898594713883",[R,"https://classroomlive-pa.googleapis.com"]);chrome.i18n.getMessage("9217362152767454370",[R]);chrome.i18n.getMessage("7604563725603697690");chrome.i18n.getMessage("533692309512814645");chrome.i18n.getMessage("7826444313570725162");chrome.i18n.getMessage("5936353814217802658");chrome.i18n.getMessage("1258929983314547244");chrome.i18n.getMessage("4491595920888170943");chrome.i18n.getMessage("8657495129257769609");
chrome.i18n.getMessage("9200475522066047621");chrome.i18n.getMessage("6042567254866620046",[R]);chrome.i18n.getMessage("7798244153502527716",[R]);chrome.i18n.getMessage("4811423455816775324",[R]);chrome.i18n.getMessage("3727581148109420602");chrome.i18n.getMessage("826991190228103925");chrome.i18n.getMessage("4748990655911819545");var Ub=chrome.i18n.getMessage("7582805180132294390",[R]);chrome.i18n.getMessage("6576961868476783976",[R]);
var Vb=function(a){return u({t:a.l,ln:a.b.name,lv:a.b.value,m:a.getMessage(),n:a.c,s:a.g,e:a.a&&a.a.message})};var S=function(){this.c=this.c;this.l=this.l};S.prototype.c=!1;S.prototype.v=function(){if(this.l)for(;this.l.length;)this.l.shift()()};var Xb=function(a){this.a=new H;if(a){a=zb(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(Wb(d),d)}}},Wb=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ea]||(a[ea]=++fa)):b.substr(0,1)+a};k=Xb.prototype;k.removeAll=function(a){a=zb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};k.remove=function(a){return this.a.remove(Wb(a))};k.clear=function(){this.a.clear()};k.contains=function(a){a=Wb(a);return I(this.a.b,a)};k.w=function(){return this.a.w()};k.L=function(){return this.a.L(!1)};
var T=function(a){S.call(this);this.g=(a||5242880)/2;this.o=!1;this.b=[];this.a=0;this.h=r(this.A,this);this.j=new Xb};t(T,S);ba(T);T.prototype.v=function(){Yb(this,!1);T.B.v.call(this)};var Yb=function(a,b){if(b!=a.o){var c=pb();if(b)jb(c,a.h);else{(c=c.a)&&Ba(c,a.h);c=a.b;if("array"!=ca(c))for(var d=c.length-1;0<=d;d--)delete c[d];c.length=0;a.a=0}a.o=b}};
T.prototype.A=function(a){if(!this.j.contains(a.c)&&a){a=Vb(a);var b=a.length;if(!(b>this.g)){var c=b-(this.g-this.a);if(b+this.a>this.g){var d=0,e=ya(this.b,function(a){d+=a.length;return d>=c},this);Fa(this.b,0,e+1);this.a-=d}Aa(this.b,a);this.a+=b}}};
var Zb=!z||9<=Number(ab);!Ta&&!z||z&&9<=Number(ab)||Ta&&A("1.9.1");z&&A("9");var $b=function(a){var b=document;return n(a)?b.getElementById(a):a},bc=function(a,b){Ia(b,function(b,d){b&&b.va&&(b=b.ua());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:ac.hasOwnProperty(d)?a.setAttribute(ac[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},ac={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",
type:"type",usemap:"useMap",valign:"vAlign",width:"width"},dc=function(a,b,c){var d=arguments,e=document,f=String(d[0]),g=d[1];if(!Zb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',sa(g.name),'"');if(g.type){f.push(' type="',sa(g.type),'"');var h={};Oa(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=e.createElement(f);g&&(n(g)?f.className=g:"array"==ca(g)?f.className=g.join(" "):bc(f,g));2<d.length&&cc(e,f,d);return f},cc=function(a,b,c){function d(c){c&&b.appendChild(n(c)?a.createTextNode(c):
c)}for(var e=2;e<c.length;e++){var f=c[e];!da(f)||q(f)&&0<f.nodeType?d(f):w(ec(f)?Da(f):f,d)}},fc=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},ec=function(a){if(a&&"number"==typeof a.length){if(q(a))return"function"==typeof a.item||"string"==typeof a.item;if(p(a))return"function"==typeof a.item}return!1};
var gc=function(a,b){var c=a.getAttribute("data-sender"),d=a.getAttribute("data-request"),e=a.getAttribute("data-params");a=a.getAttribute("data-expectResponse");if(!c)return b&&C(b,"Missing data-sender attribute"),null;if(!d)return b&&C(b,"Missing data-request attribute"),null;if(a)a=a==(!0).toString();else return b&&C(b,"Missing data-response attribute"),null;if(e)try{var f=JSON.parse(e)}catch(g){if(g instanceof SyntaxError)return b&&C(b,"Invalid data-params attribute"),null}return{sender:c,request:d, params:f,expectResponse:a}};
var U=function(a,b,c){E.call(this,a,b,c,"connection")};t(U,E);U.prototype.name="edulive.messaging.Error";var hc=function(a,b){this.type=a;this.a=this.target=b;this.ha=!0};var ic=function(a,b){hc.call(this,b.request,a);this.message=b};t(ic,hc);z&&A("9");!Ua||A("528");Ta&&A("1.9b")||z&&A("8")||Ra&&A("9.5")||Ua&&A("528");Ta&&!A("8")||z&&A("9");var jc="closure_listenable_"+(1E6*Math.random()|0),kc=0;var lc=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.N=e;this.key=++kc;this.removed=this.M=!1},mc=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.N=null};var nc=function(a){this.src=a;this.a={};this.b=0};nc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=oc(e,b,c,d);return-1<b?(mc(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};var pc=function(a,b){var c=b.type;c in a.a&&Ba(a.a[c],b)&&(mc(b),0==a.a[c].length&&(delete a.a[c],a.b--))};
nc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,mc(d[e]);delete this.a[c];this.b--}return b};var oc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.N==d)return e}return-1};
var qc="closure_lm_"+(1E6*Math.random()|0),rc={},sc=0,tc=function(a,b,c,d,e){if("array"==ca(b))for(var f=0;f<b.length;f++)tc(a,b[f],c,d,e);else(d=q(d)?!!d.capture:!!d,c=uc(c),a&&a[jc])?a.b.remove(String(b),c,d,e):a&&(a=vc(a))&&(b=a.a[b.toString()],a=-1,b&&(a=oc(b,c,d,e)),(c=-1<a?b[a]:null)&&"number"!=typeof c&&c&&!c.removed&&((e=c.src)&&e[jc]?pc(e.b,c):(b=c.type,d=c.proxy,e.removeEventListener?e.removeEventListener(b,d,c.capture):e.detachEvent&&e.detachEvent(b in rc?rc[b]:rc[b]="on"+b,d),sc--,(b=
vc(e))?(pc(b,c),0==b.b&&(b.src=null,e[qc]=null)):mc(c))))},vc=function(a){a=a[qc];return a instanceof nc?a:null},wc="__closure_events_fn_"+(1E9*Math.random()>>>0),uc=function(a){if(p(a))return a;a[wc]||(a[wc]=function(b){return a.handleEvent(b)});return a[wc]};
var V=function(){S.call(this);this.b=new nc(this);this.V=this;this.D=null};t(V,S);V.prototype[jc]=!0;V.prototype.removeEventListener=function(a,b,c,d){tc(this,a,b,c,d)};V.prototype.v=function(){V.B.v.call(this);this.b&&this.b.removeAll(void 0);this.D=null};V.prototype.listen=function(a,b,c,d){var e=this.b,f=String(a).toString();a=e.a[f];a||(a=e.a[f]=[],e.b++);var g=oc(a,b,c,d);-1<g?(b=a[g],b.M=!1):(b=new lc(b,e.src,f,!!c,d),b.M=!1,a.push(b));return b}; var xc=function(a,b,c,d){b=a.b.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.capture==c){var h=g.listener,F=g.N||g.src;g.M&&pc(a.b,g);e=!1!==h.call(F,d)&&e}}return e&&0!=d.ha};
var yc=function(a,b,c){this.g=c;this.c=a;this.h=b;this.b=0;this.a=null};yc.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.c();return a};var zc=function(a,b){a.h(b);a.b<a.g&&(a.b++,b.next=a.a,a.a=b)};var Ac=function(a){l.setTimeout(function(){throw a;},0)},Bc,Cc=function(){var a=l.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!y("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;
a=r(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!y("Trident")&&!y("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m(c.next)){c=c.next;var a=c.U;c.U=null;a()}};return function(a){d.next={U:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b= document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){l.setTimeout(a,0)}};
var Dc=function(){this.b=this.a=null},Fc=new yc(function(){return new Ec},function(a){a.reset()},100);Dc.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Ec=function(){this.next=this.b=this.a=null};Ec.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Ec.prototype.reset=function(){this.next=this.b=this.a=null};
var Kc=function(a,b){Gc||Hc();Ic||(Gc(),Ic=!0);var c=Jc,d=Fc.get();d.set(a,b);c.b?c.b.next=d:c.a=d;c.b=d},Gc,Hc=function(){if(-1!=String(l.Promise).indexOf("[native code]")){var a=l.Promise.resolve(void 0);Gc=function(){a.then(Lc)}}else Gc=function(){var a=Lc;!p(l.setImmediate)||l.Window&&l.Window.prototype&&!y("Edge")&&l.Window.prototype.setImmediate==l.setImmediate?(Bc||(Bc=Cc()),Bc(a)):l.setImmediate(a)}},Ic=!1,Jc=new Dc,Lc=function(){for(var a;a=Jc.remove();){try{a.a.call(a.b)}catch(b){Ac(b)}zc(Fc, a)}Ic=!1};
var W=function(a,b){this.a=0;this.j=void 0;this.g=this.b=this.c=null;this.h=this.l=!1;this.o=[];Mc(this,Error("created"));this.A=0;if(a!=aa)try{var c=this;a.call(b,function(a){Nc(c,2,a)},function(a){Nc(c,3,a)})}catch(d){Nc(this,3,d)}},Oc=function(){this.next=this.g=this.b=this.h=this.a=null;this.c=!1};Oc.prototype.reset=function(){this.g=this.b=this.h=this.a=null;this.c=!1};var Pc=new yc(function(){return new Oc},function(a){a.reset()},100),Qc=function(a,b,c){var d=Pc.get();d.h=a;d.b=b;d.g=c;return d};
W.prototype.then=function(a,b,c){Mc(this,Error("then"));return Rc(this,p(a)?a:null,p(b)?b:null,c)};W.prototype.then=W.prototype.then;W.prototype.$goog_Thenable=!0;W.prototype.cancel=function(a){0==this.a&&Kc(function(){var b=new Sc(a);Tc(this,b)},this)};
var Tc=function(a,b){if(0==a.a)if(a.c){var c=a.c;if(c.b){for(var d=0,e=null,f=null,g=c.b;g&&(g.c||(d++,g.a==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.a&&1==d?Tc(c,b):(f?(d=f,d.next==c.g&&(c.g=d),d.next=d.next.next):Uc(c),Vc(c,e,3,b)))}a.c=null}else Nc(a,3,b)},Xc=function(a,b){a.b||2!=a.a&&3!=a.a||Wc(a);a.g?a.g.next=b:a.b=b;a.g=b},Rc=function(a,b,c,d){var e=Qc(null,null,null);e.a=new W(function(a,g){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(G){g(G)}}:a;e.b=c?function(b){try{var e=c.call(d,
b);!m(e)&&b instanceof Sc?g(b):a(e)}catch(G){g(G)}}:g});e.a.c=a;Xc(a,e);return e.a};W.prototype.C=function(a){this.a=0;Nc(this,2,a)};W.prototype.D=function(a){this.a=0;Nc(this,3,a)};
var Nc=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;a:{var d=c,e=a.C,f=a.D;if(d instanceof W){Mc(d,Error("then"));Xc(d,Qc(e||aa,f||null,a));var g=!0}else{if(d)try{var h=!!d.$goog_Thenable}catch(G){h=!1}else h=!1;if(h)d.then(e,f,a),g=!0;else{if(q(d))try{var F=d.then;if(p(F)){Yc(d,F,e,f,a);g=!0;break a}}catch(G){f.call(a,G);g=!0;break a}g=!1}}}g||(a.j=c,a.a=b,a.c=null,Wc(a),3!=b||c instanceof Sc||Zc(a,c))}},Yc=function(a,b,c,d,e){var f=!1,g=function(a){f||
(f=!0,c.call(e,a))},h=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,g,h)}catch(F){h(F)}},Wc=function(a){a.l||(a.l=!0,Kc(a.H,a))},Uc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.g=null);return b};W.prototype.H=function(){for(var a;a=Uc(this);)this.A++,Vc(this,a,this.a,this.j);this.l=!1};
var Vc=function(a,b,c,d){if(3==c&&b.b&&!b.c)for(;a&&a.h;a=a.c)a.h=!1;if(b.a)b.a.c=null,$c(b,c,d);else try{b.c?b.h.call(b.g):$c(b,c,d)}catch(e){ad.call(null,e)}zc(Pc,b)},$c=function(a,b,c){2==b?a.h.call(a.g,c):a.b&&a.b.call(a.g,c)},Mc=function(a,b){if(n(b.stack)){var c=b.stack.split("\n",4)[3];b=b.message;b+=Array(11-b.length).join(" ");a.o.push(b+c)}},Zc=function(a,b){a.h=!0;Kc(function(){if(a.h){if(b&&n(b.stack)&&a.o.length){for(var c=["Promise trace:"],d=a;d;d=d.c){for(var e=a.A;0<=e;e--)c.push(d.o[e]); c.push("Value: ["+(3==d.a?"REJECTED":"FULFILLED")+"] <"+String(d.j)+">")}b.stack+="\n\n"+c.join("\n")}ad.call(null,b)}})},ad=Ac,Sc=function(a){v.call(this,a)};t(Sc,v);Sc.prototype.name="cancel";
var bd=function(a,b,c){S.call(this);this.a=a;this.h=b||0;this.b=c;this.g=r(this.ga,this)};t(bd,S);k=bd.prototype;k.G=0;k.v=function(){bd.B.v.call(this);this.stop();delete this.a;delete this.b};k.start=function(a){this.stop();var b=this.g;a=m(a)?a:this.h;if(!p(b))if(b&&"function"==typeof b.handleEvent)b=r(b.handleEvent,b);else throw Error("Invalid listener argument");this.G=2147483647<Number(a)?-1:l.setTimeout(b,a||0)};k.stop=function(){0!=this.G&&l.clearTimeout(this.G);this.G=0}; k.ga=function(){this.G=0;this.a&&this.a.call(this.b)};
var X=function(a,b){V.call(this);this.a=a;this.id=b||window.location.pathname;this.Z=!("undefined"==typeof window.chrome||!chrome||!chrome.runtime)};t(X,V);X.prototype.sendRequest=function(a,b,c){return new W(function(d,e){var f={sender:this.id,request:a,params:b,expectResponse:!0};var g=c||4E4;g=new bd(r(this.fa,this,d,e,f),g);d=r(this.ea,this,d,e,f,g);rb(this.a,this.id+": Sending (and expect response):"+u(f));this.sendMessage(f,d);g.start()},this)};
X.prototype.sendMessage=function(a,b){if(!this.Z)throw new U("Not running in Chrome.",navigator.appVersion);chrome.runtime.sendMessage(a,b)};
X.prototype.ea=function(a,b,c,d,e){var f=chrome.runtime.lastError;d.c||(d.c=!0,d.v());f?(C(this.a,this.id+": Failed sending "+c.request+". Reason: "+f.message),b(new U("Failed to dispatch message. There was no recipient to receive the message.",f))):q(e)&&(m(e.response)||m(e.error))?(d=this.a,c=this.id+": Received response: "+u(e)+" for message: "+u(c),d&&d.log(e.error?fb:ib,c,void 0),m(e.response)?a(e.response):b(new vb(e.error))):b(new U("Invalid response from message request.",u(e)))}; X.prototype.fa=function(a,b,c){C(this.a,this.id+": Failed to receive a response to "+c.request+" in the time alotted.");b(new U("Failed to receive a response in the time alotted.",c.request,Ub))};
var cd=function(a){var b=["sender","request","expectResponse"];if(!q(a))return!1;q(b)&&(b=Ka(b));return wa(b,function(b){return Ma(a,b)})};var Y=function(a,b){b=b||qb("edulive.messaging.InternalMessageDispatcher");X.call(this,b,a);this.j=r(this.aa,this);chrome.runtime.onMessage.addListener(this.j);chrome.runtime.onMessageExternal&&chrome.runtime.onMessageExternal.addListener(this.j);this.P=r(this.W,this);chrome.runtime.onConnectExternal&&chrome.runtime.onConnectExternal.addListener(this.P);this.K={};this.g={};this.J={}};t(Y,X);ba(Y);
Y.prototype.v=function(){w(La(this.g),function(a){dd(this,a,!0)},this);this.K={};chrome.runtime.onConnectExternal&&chrome.runtime.onConnectExternal.removeListener(this.P);chrome.runtime.onMessageExternal&&chrome.runtime.onMessageExternal.removeListener(this.j);chrome.runtime.onMessage.removeListener(this.j);Y.B.v.call(this)};Y.prototype.sendMessage=function(a,b){b?ed(this,a,b)||Y.B.sendMessage.call(this,a,b):(Kc(r(this.H,this,a)),Y.B.sendMessage.call(this,a,b),fd(this,a))};
var fd=function(a,b){Ia(a.g,function(a){a.postMessage(b)},a)};Y.prototype.aa=function(a,b,c){if(!m(a)||!q(a))return!1;if(!cd(a))return C(this.a,this.id+": Invalid message: "+u(a)+" from: "+u(b)),!1;if(a.sender==this.id)return!1;rb(this.a,this.id+": Received message: "+u(a)+" from: "+u(b));if(a.expectResponse)return this.T(b.id,a,c);this.H(a);return!1};
Y.prototype.H=function(a){var b=new ic(this,a),c;if(a=this.D)for(c=[];a;a=a.D)c.push(a);a=this.V;var d=b.type||b;if(n(b))b=new hc(b,a);else if(b instanceof hc)b.target=b.target||a;else{var e=b;b=new hc(d,a);Oa(b,e)}e=!0;if(c)for(var f=c.length-1;0<=f;f--){var g=b.a=c[f];e=xc(g,d,!0,b)&&e}g=b.a=a;e=xc(g,d,!0,b)&&e;e=xc(g,d,!1,b)&&e;if(c)for(f=0;f<c.length;f++)g=b.a=c[f],e=xc(g,d,!1,b)&&e};Y.prototype.T=function(a,b,c){return a==chrome.runtime.id&&b.sender==this.id?!1:ed(this,b,c)};
var ed=function(a,b,c){var d=b.request;if(!Ma(a.K,d))return!1;var e=new ic(a,b);try{var f=(0,a.K[d])(e);if(f){var g=r(a.da,a,b,c),h=r(a.A,a,b,c);f.then(g,h)}return!!f}catch(F){return a.A(b,c,F),!1}};Y.prototype.da=function(a,b,c){try{JSON.stringify(c),rb(this.a,"Responding to "+u(a)+" with "+u(c)),b({response:c})}catch(d){this.A(a,b,d)}};
Y.prototype.A=function(a,b,c){if("Attempting to use a disconnected port object"==c.message)C(this.a,a.sender+" disconnected! Cannot respond to "+u(a));else{c instanceof Error&&(c=new vb(c));try{JSON.stringify(c),C(this.a,"Responding to "+u(a)+" with the error "+u(c)),b({error:Object(c)})}catch(d){C(this.a,"Failed to serialize: "+(p(c.toString)?c.toString():c)+". Returning "+(p(d.toString)?d.toString():d)+" instead."),this.A(a,b,d)}}};
var dd=function(a,b,c){var d=a.a;d&&d.log(gb,"Ending connection with "+b,void 0);if(d=a.g[b]){var e=a.g;b in e&&delete e[b];c&&d.disconnect();c=a.J[b];a=a.J;b in a&&delete a[b];d.onDisconnect.removeListener(c)}};
Y.prototype.W=function(a){if(a.name!=this.id)rb(this.a,"Ignoring connection from "+JSON.stringify(a)+" because it is for another page.");else{var b=a.sender;if(b){var c=[];b.id&&c.push(b.id);b.url&&c.push(b.url);c.length?(b=c.join("|"),Ma(this.g,b)?(C(this.a,"Already have a connection with "+b+". Disconnecting"),a.disconnect()):((c=this.a)&&c.log(gb,"Establishing connection with "+b,void 0),this.g[b]=a,c=r(this.X,this,b),a.onDisconnect.addListener(c),this.J[b]=c)):(C(this.a,"Could not find an id for "+ JSON.stringify(a)+". Disconnecting."),a.disconnect())}}};Y.prototype.X=function(a){dd(this,a)};
var Z=function(a){this.h=chrome.runtime.id;Y.call(this,a||"messaging:"+this.h,qb("edulive.messaging.InjectedMessageDispatcher"));this.C=gd("messaging:"+this.h);this.ca=gd("requests:"+this.h,this.C);this.Y=gd("events:"+this.h,this.C);this.S=new MutationObserver(r(this.$,this));this.S.observe(this.ca,{childList:!0});this.o={};(a=this.a)&&a.log(gb,"Installed for "+this.h,void 0)};t(Z,Y);ba(Z);Z.prototype.v=function(){this.S.disconnect();Ia(this.o,function(a){a.cancel()},this);this.o={};fc(this.C);Z.B.v.call(this)};
Z.prototype.H=function(a){var b=this.Y;do var c=["message",a.sender,a.request,ja(),Math.floor(1E6*Math.random())].join(":");while($b(c));c=dc("DIV",{id:c,style:"display:none"});c.setAttribute("data-sender",a.sender);c.setAttribute("data-request",a.request);c.setAttribute("data-expectResponse",a.expectResponse);m(a.params)&&c.setAttribute("data-params",JSON.stringify(a.params));b&&b.appendChild(c)};Z.prototype.T=function(){return!1};
var gd=function(a,b){var c={};b=b||document.body;c.id=a;c.style="display:none";a=dc("DIV",c);b.appendChild(a);return a};
Z.prototype.$=function(a){a&&w(a,function(a){a.addedNodes&&w(Da(a.addedNodes),function(a){var b=a.getAttribute("id")||"unknown";if((a=gc(a,this.a))&&a.expectResponse){var c=r(this.R,this,b,"data-response"),f=r(this.R,this,b,"data-error");a=this.sendRequest(a.request,a.params).then(c,f);c=r(this.ba,this,b);Mc(a,Error("thenAlways"));c=Qc(c,c,void 0);c.c=!0;Xc(a,c);this.o[b]=a}else C(this.a,"Skipping invalid request "+b)},this)},this)}; Z.prototype.R=function(a,b,c){var d=$b(a);d?d.setAttribute(b,JSON.stringify(c)):C(this.a,a+" was removed before the response was received.")};Z.prototype.ba=function(a){var b=this.o;a in b&&delete b[a]};
(function(a,b){T.I();var c=b||za(function(a){return"INFO"==a.name});a=a||!/^[\s\xa0]*$/.test("")&&[""];b="HangingGetChannel LcsPushChannel invalidation-hr goog.net.BrowserChannel webmonitoring.MemoryUsageReporter wiz.Dispatcher goog.net.NetworkTester BrowserChannelImpl bc-watchdog".split(" ");var d=T.I();null!=c&&kb(pb(),c);if(a&&0<a.length){c=function(a){d.A(a)};for(var e=0;e<a.length;++e)jb(qb(a[e]),c)}else Yb(d,!0);b&&0<b.length&&w(b,function(a){d.j.a.set(Wb(a),a)})})();Z.I(); document.addEventListener("unload",function(){var a=Z.I();a.c||(a.c=!0,a.v())});

}catch(e){_DumpException(e)}
/* _GlobalSuffix_ */
// Google Inc.
