var b,q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)},v="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function w(){w=function(){};v.Symbol||(v.Symbol=y)}var y=function(){var a=0;return function(c){return"jscomp_symbol_"+(c||"")+a++}}();
function z(){w();var a=v.Symbol.iterator;a||(a=v.Symbol.iterator=v.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&q(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return A(this)}});z=function(){}}function A(a){var c=0;return B(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})}function B(a){z();a={next:a};a[v.Symbol.iterator]=function(){return this};return a}
function C(a,c){z();a instanceof String&&(a+="");var d=0,e={next:function(){if(d<a.length){var f=d++;return{value:c(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}function D(a){if(a){for(var c=v,d=["Array","prototype","keys"],e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];a=a(e);a!=e&&null!=a&&q(c,d,{configurable:!0,writable:!0,value:a})}}
D(function(a){return a?a:function(){return C(this,function(a){return a})}});var G=G||{};G.a={};G.a.Ca="config";G.a.U="options";G.a.pb="playerState";G.a.K="domain";G.a.B="uuid";G.a.w="logping";G.a.v="installedTimestamp";G.a.nb="completedCoreLessons";G.a.ga=["idkloemkmldbemijiamdiolojbffnjlh","lgjgggmkddgppdhndhmhgjaaoghdfnen"];G.a.Ea="http://localhost:8888";G.a.Ba="https://synergysetraining.appspot.com";G.a.ha="video";G.a.mb="cms";G.a.M=G.a.Ba;
G.a.Ra=function(){if(chrome&&chrome.runtime)for(var a=0,c=G.a.ga.length;a<c;a++)if(chrome.runtime.id==G.a.ga[a])return!0;return!1};G.a.b=function(){if(1>arguments.length||!arguments[0])return!1;for(var a=arguments[0],c=1,d=arguments.length;c<d;c++){var e=arguments[c];if("undefined"===typeof a[e])return!1;a=a[e]}return!0};
G.a.Qa=function(){if(1>arguments.length||!arguments[0])return!1;for(var a=arguments[0],c=1,d=arguments.length;c<d;c++){var e=arguments[c];if("undefined"===typeof a[e])return!1;a=a[e]}return!0===a||1===a||"1"===a};G.a.lb=function(){var a=G.options;"dev"==a.runMode?G.a.M=G.a.Ea:a.serverAddress&&("simple"==a.runMode||G.a.Ra()?(console.log("Options changed server address to "+a.serverAddress),G.a.M=a.serverAddress):console.log("Only Chrome Store and dev extensions can change server address."))};
G.a.Y=function(a,c){var d=null,e=document.createElement("a");e.href=c;c=e.hostname;e=e.pathname;for(var f in a)if(a.hasOwnProperty(f)){var h=f.split("-");if(!(2>h.length||"domain"!=h[0])){h=h[1];var g=a[f];if(c==g){if(!d||d.value.length<g.length)d={na:h,value:g}}else{var m=g.indexOf("/");if(0<m){var k=g.substring(m);m=e.indexOf(k);k=m+k.length;0<=m&&(e.length==k||e.length>k&&"/"==e.charAt(k))&&(!d||d.value.length<g.length)&&(d={na:h,value:g})}}}}return d?d.na:null};
G.a.Za=function(a){var c=a.indexOf("?"),d=a.indexOf("#");d=0<=d?d:a.length;var e={};a=a.substring(0<=c?c+1:0,d).split("&");c=0;for(d=a.length;c<d;c++){var f=a[c].split("=",2);if(2==f.length){var h=decodeURIComponent(f[0]);f=f[1].replace(/\+/g," ");e[h]=decodeURIComponent(f)}}return e};G.a.zb=function(a){try{var c=document.createElement("a");c.href=a;var d=c.pathname.split("/");a=0;for(var e=d.length;a<e;a++)d[a]=G.a.ca(d[a]);return c.protocol+"//"+c.host+d.join("/")+G.a.ca(c.search)+G.a.ca(c.hash)}catch(f){return"Malformed"}};
G.a.aa=function(a){return 0==a.search("https?://(?:www.)?synergyse.com/shared?")||0==a.search("https?://(?:portal.)?synergyse.com/shared?")||0==a.search("http://localhost:8080/shared?")};G.a.ca=function(a){return!a||4>a.length?a:a.charAt(0)+"..."+a.charAt(a.length-1)};
G.a.Ab=function(a,c){function d(a){var c={},d;for(d in a)c[a[d]]=1;return c}if(a||!G.a.b(c,"content"))return null;c=c.content;a=G.a.ab(G.a.b(c,"data")?c.data:[],d(c.unpublishedModuleScriptIds),d(c.unpublishedModuleSectionIds),d(c.unpublishedContentScriptIds),d(c.unpublishedContentSectionIds),d(c.recommendedModuleScriptIds),d(c.recommendedContentScriptIds));G.a.b(c,"lessonEditorIds")&&G.a.bb(a,d(c.lessonEditorIds));G.a.b(c,"customSections")&&G.a.b(c,"customLessons")&&G.a.cb(a,c.customSections,c.customLessons);
G.a.b(c,"userStatesMap")&&G.a.eb(a,c.userStatesMap);return a};
G.a.ab=function(a,c,d,e,f,h,g){function m(c,d){for(var e={},f=0,h=a.length;f<h;f++){var g=a[f];if(g.type==c&&g.parentContentId==d){var l=g.contentId,k=g.name;g=g.value;if("alias"==c&&"targets"==k)"undefined"===typeof e[k]&&(e[k]=[]),e[k].push(g);else if("lesson"==c&&"lessonEventArray"==k)"undefined"===typeof e.events&&(e.events=[]),e.events.push(m("lessonEvent",l));else if("lesson"==c&&"lessonLinkArray"==k)"undefined"===typeof e.links&&(e.links=[]),e.links.push(m("lessonLink",l));else if("section"==
c&&"lessonIdArray"==k)try{var n=JSON.parse(g),p=n.index;for("undefined"===typeof e.ids&&(e.ids=[]);e.ids.length<=p;)e.ids.push(0);e.ids[p]=n.contentId}catch(T){G.log(G.h,"Failed to parse section lesson id order "+g)}else{if("allowSkip"==k||"equals"==k||"monitorMousedown"==k||"saveState"==k)g=g&&"0"!==g&&"false"!==g;k=k.replace(/Url$/,"");g&&1<g.length&&":"==g.charAt(0)&&("undefined"!==typeof u[g]?g=u[g]:G.log(G.h,"New item is missing alias id. type="+c+" name="+k+" value="+g+" contentId="+l));e[k]=
g}}}return e}for(var k={aliases:{},scripts:{},sections:{},sectionOrder:[],externalScriptIds:{}},u={},l=0,r=a.length;l<r;l++){var n=a[l],p=n.contentId;"alias"==n.type&&"id"==n.name&&(u[n.value]=":"+p)}l=0;for(r=a.length;l<r;l++)if(n=a[l],p=n.contentId,"alias"==n.type&&"id"==n.name){var t=m("alias",p);t.externalId=n.value;t.contentId=p;k.aliases[":"+p]=t}else if("lesson"==n.type&&"id"==n.name){if(!G.a.b(c,n.value)&&!G.a.b(e,p)){t=m("lesson",p);var x=n.value;t.externalId=x;G.a.b(k,"externalScriptIds",
x)&&G.log(G.h,"Module data already processed this external id: "+x);k.externalScriptIds[x]=p;t.contentId=p;G.a.b(n,"modifiedTimestamp")&&(t.modifiedTimestamp=n.modifiedTimestamp);G.a.b(n,"publishedTimestamp")&&(t.publishedTimestamp=n.publishedTimestamp);k.scripts[p]=t;if(G.a.b(h,n.value)||G.a.b(g,p))t.recommended=!0}}else if("section"==n.type&&"id"==n.name)G.a.b(d,n.value)||G.a.b(f,p)||(t=m("section",p),t.externalId=n.value,t.contentId=p,k.sections[p]=t);else if("sectionOrder"==n.type)try{for(var E=
JSON.parse(n.value),F=E.index;k.sectionOrder.length<=F;)k.sectionOrder.push(0);k.sectionOrder[F]=E.contentId}catch(S){G.log(G.h,"Failed to parse section order "+n.value)}for(p in k.scripts)k.scripts.hasOwnProperty(p)&&(c=k.scripts[p],G.a.b(c,"events")&&c.events.sort(function(a,c){return a===c||!G.a.b(a,"time")&&!G.a.b(c,"time")?0:G.a.b(a,"time")?G.a.b(c,"time")?+a.time-c.time:-1:1}));return k};
G.a.$a=function(a){for(var c={},d=0,e=a.length;d<e;d++){var f=a[d],h="id"==f.name?f.contentId:f.parentContentId;if(G.a.b(c,h))var g=c[h];else g={},g.contentId=h,g.app2Id=h,g.ownerClientId=f.ownerClientId,c[h]=g;"id"==f.name?(g.appId=f.value,g.externalId=f.value):"title"==f.name&&f.value?(g.name=f.value,g.title=f.value):"parentObjectOrderPosition"==f.name&&f.value&&(g.parentObjectOrderPosition=f.value)}a=[];for(var m in c)c.hasOwnProperty(m)&&(g=c[m],G.a.b(g,"externalId")&&G.a.b(g,"name")&&a.push(c[m]));
G.a.jb(a);return a};G.a.ub=function(a){G.a.b(a,"appsData")&&(a.apps=G.a.$a(a.appsData))};
G.a.cb=function(a,c,d){function e(a,c){return f(a,c,m)}function f(a,c,d){return a==c?0:G.a.b(d,a,"position")?G.a.b(d,c,"position")?+d[a].position-d[c].position:-1:G.a.b(d,c,"position")?1:0}for(var h=[],g={},m={},k=0,u=c.length;k<u;k++){var l=c[k],r="custom"+l.customSectionId;g[r]=l;l.externalId=r;l.isCustom=!0;l.ids=[];a.sections[r]=l;h.push(r)}k=0;for(u=d.length;k<u;k++)l=d[k],c="custom"+l.customLessonId,m[c]=l,l.externalId=c,l.recommended=l.isRecommended,l.isCustom=!0,G.a.b(l,"videoUrl")&&(l.video=
l.videoUrl),a.scripts[c]=l,r="custom"+(G.a.b(l,"customSectionId")?l.customSectionId:0),G.a.b(a,"sections",r)?(l=a.sections[r],l.ids.push(c)):"custom0"==r&&(l={title:"Custom lessons",isCustom:!0,ids:[]},l.ids.push(c),a.sections[r]=l,h.push(r));h.sort(function(a,c){return f(a,c,g)});k=0;for(u=h.length;k<u;++k)d=h[k],G.a.b(a,"sections",d)?(l=a.sections[d],G.a.b(l,"ids")?l.ids.sort(e):G.log(G.l,"Custom section does not have ids array. customSectionId="+d)):G.log(G.h,"customSectionId is missing from sections. customSectionId="+
d);h.length&&(a.sectionOrder=h.concat(a.sectionOrder))};G.a.bb=function(a,c){for(var d in a.scripts)G.a.b(c,d)&&(a.scripts[d].isEditor=!0,a.isEditor=!0)};
G.a.eb=function(a,c){for(var d in a.scripts){var e=a.scripts[d],f=G.a.Qa(e,"isCustom")?d:e.externalId;G.a.b(c,f)?(f=c[f],e.playerState=f.playerState||"not_started",e.menuState=f.menuState||"not_started",e.newToUser=!!f.newToUser,!e.newToUser||"start"!=e.playerState&&0!=e.playerState.indexOf("progress")&&"complete"!=e.playerState||(e.newToUser=!1)):e.newToUser=!0}};G.a.wb=function(a){return a&&"string"===typeof a&&0==a.indexOf("custom")};G.a.xb=function(a){return a&&"string"===typeof a&&0==a.indexOf("custom")};
G.a.vb=function(a){return a&&"string"===typeof a&&0==a.indexOf("custom")};G.a.yb=function(a){switch(a){case "manager":return!0;case "app":return!0;case "lesson":return!0;case "translate":return!0;case "audio":return!0;case "video":return!0;default:return!1}};
G.a.jb=function(a){a.sort(function(a,d){return G.a.b(a,"parentObjectOrderPosition")||G.a.b(d,"parentObjectOrderPosition")?G.a.b(a,"parentObjectOrderPosition")?G.a.b(d,"parentObjectOrderPosition")?a.parentObjectOrderPosition-d.parentObjectOrderPosition:-1:1:0})};G.a.ib=function(a,c,d,e,f,h){a()?c():0>=h?d():window.setTimeout(function(){G.a.ib(a,c,d,e*f,f,--h)},e*(1.3-.6*Math.random()))};G.f=function(){};G.f.prototype.data=null;G.f.prototype.source=null;G.f.prototype.j={};G.f.V="local";G.f.la="storage";G.f.J="server";b=G.f.prototype;b.set=function(a,c,d){this.source=a;this.data||(this.data={});a=!1;for(var e in c)!c.hasOwnProperty(e)||"undefined"!==typeof this.data[e]&&this.data[e]==c[e]||(this.data[e]=c[e],a=!0);if(!d)for(e in this.data)this.data.hasOwnProperty(e)&&!c.hasOwnProperty(e)&&(delete this.data[e],a=!0);return a};b.get=function(a){return this.has(a)?this.data[a]:null};
b.has=function(a){return G.a.b(this.data,a)};function H(a,c){var d=[];if(!a.data||!c)return d;c=c.toLowerCase();for(var e in a.data)a.data.hasOwnProperty(e)&&0==e.indexOf(c)&&d.push(a.data[e]);return d}function I(){var a=G.f.i(),c="domain",d={};if(!a.data||!c)return d;c=c.toLowerCase();for(var e in a.data)a.data.hasOwnProperty(e)&&0==e.indexOf(c)&&(d[e]=a.data[e]);return d}
function J(a,c,d){var e=null,f=c==G.f.J?G.a.M+"/ajax/data?path=settings":chrome.extension.getURL("/config/chrome.compiled.json");f||d();c==G.f.J&&(e=setTimeout(function(){d()},5E3));G.W(f,function(f,g){if(f)return G.log(G.h,f),d();clearTimeout(e);if(!g)return d();f=G.a.b(g,"settingsData")?g.settingsData:g;if(!f)return d();g=!1;var h=a.get("user-email")&&!f["user-email"];a.set(c,f,h)&&(g=!0);G.log(G.l,"Updated settings from "+c);c==G.f.J&&(K(a),g&&a.kb("change"));d()})}
function L(a,c){G.storage.get(null,function(d){if(G.a.b(d,M(0))){if(a.data&&a.source&&a.source!=G.f.V)return c();G.log(G.l,"Updated settings from storage");(d=N(d))&&a.set(G.f.la,d)}c()})}function M(a){return G.a.Ca+(0<a?"_"+a:"")}
function K(a){if(a.data){var c=G.storage.QUOTA_BYTES_PER_ITEM;4096>c?(G.log(G.h,"Unexpected quota bytes is less than 4096: "+c),c=4096):8192<c&&G.log(G.l,"Quota bytes is larger than 8192: "+c);var d={};a=JSON.stringify(a.data);for(var e=0;;){var f=M(e),h=c-f.length-8,g=h,m=a.substr(0,g);if(0>=m.length){G.log(G.h,"Unexpected part data size in settings");return}if(m.length>h/2){var k=JSON.stringify(m);k&&k.length>h&&(g-=Math.max(k.length-m.length+1,1),m=a.substr(0,g))}if(0>=m.length){G.log(G.h,"Unexpected part data size in settings after trimming due to escaped characters");
return}d[f]=m;if(0>=a.length-m.length)break;a=a.substr(m.length);e++}G.storage.remove(M(e+1),function(){G.storage.set(d,function(){if(chrome.runtime.lastError){for(var a=[],c=0;c<=e;c++)a.push(JSON.stringify(d[M(c)]).length);G.log(G.h,"Failed to store settings. errorMsg="+chrome.runtime.lastError.message+" lengths="+a.join(","))}})})}else G.log(G.h,"Tried to save empty settings data, skipping")}
function N(a){if(!G.a.b(a,M(0)))return null;var c=M(0);if("string"!==typeof a[c])return a[c];c="";for(var d=0;d<G.storage.MAX_ITEMS;d++){var e=M(d);if(!G.a.b(a,e))break;c+=a[e]}try{return JSON.parse(c)}catch(f){return 100<c.length&&(c=c.substr(0,50)+"..."+c.substr(-50)),G.log(G.h,"Error parsing dataStr into JSON. errMsg="+f.message+" dataStr="+c),null}}
b.update=function(a){function c(){G.log(G.l,"Loading storage config");L(f,d)}function d(){G.log(G.l,"Loading settings from the server");G.storage.get(G.a.v,function(){chrome.runtime.lastError&&G.log(G.h,"Failed to get installation time from storage.");G.tb();J(f,G.f.J,e)})}function e(){G.log(G.Da,"Settings.update loaded something");f.data&&a&&(G.log(G.Da,"Settings.update ready, going to next"),a(),a=null)}var f=this;G.log(G.l,"Updating settings hasData="+!!this.data);this.data?d():(G.log(G.l,"Loading local settings"),
J(this,G.f.V,c))};function O(a,c){var d=G.f.i();if(d.data)a();else{var e=function(){var c=chrome.extension.getURL("/config/chrome.compiled.json");c?G.W({url:c},function(c){c&&c.data?(c=c.data,G.a.b(c,"settingsData")&&(c=c.settingsData),d.set(G.f.V,c),a()):console.error("Failed to parse local config.")}):console.error("Failed to get local config.")};c?e():G.storage.get(null,function(c){if(G.a.b(c,M(0)))return(c=N(c))&&d.set(G.f.la,c),a();e()})}}
b.bind=function(a,c){a=a.split(" ");for(var d=0,e=a.length;d<e;d++){var f=a[d];G.a.b(this.j,f)||(this.j[f]=[]);this.j[f].push(c)}};b.unbind=function(a){a=a.split(" ");for(var c=0,d=a.length;c<d;c++){var e=a[c];G.a.b(this.j,e)&&(this.j[e]=null,delete this.j[e])}};b.kb=function(a){for(var c in this.j)if(c.split(".")[0]==a&&G.a.b(this.j,c))for(var d=this.j[c],e=0,f=d.length;e<f;e++){var h=d[e];h&&h.apply(this,arguments)}};G.f.i=function(){"undefined"===typeof G.settings&&(G.settings=new G.f);return G.settings};G.g=function(){};G.g.ia=1E3;G.g.ja=2E3;G.g.Ha=18E4;G.g.ma="X-Xsrf-Token";b=G.g.prototype;b.H=[];b.Z=!1;b.F=G.g.ia;b.P=G.g.ja;b.O=0;b.R=0;b.o=null;b.ua=!1;b.fa=null;
b.send=function(a,c,d,e){var f=!1;if("POST"==a&&c){var h=document.createElement("a");h.setAttribute("href",c);h.hostname&&(f=0==h.hostname.indexOf("test"),f=0==h.hostname.indexOf("dev")||f)}G.log&&"object"!=typeof d&&G.log(G.h,"Params is not a JSON object. type="+typeof d+" params="+String(d).substr(0,50));a={method:a,url:c,ta:d,X:e,withCredentials:f};this.ua&&(a.method="GET",a.url=a.url.replace(/[?&=]/g,"-")+".json");this.H.push(a);P(this)};
function P(a,c){if(!(0>=a.H.length||a.Z&&!c)){a.Z=!0;a.c=new XMLHttpRequest;a.sa=!1;c=a.H[0];var d=+new Date;0>=a.O&&(a.O=d,a.R=0,a.o=null);a.c.onerror=function(){if(!a.sa){a.sa=!0;a.o||(a.o="Connection error.");var c=Math.round(a.F*(1.3-.6*Math.random()));a.R=d+c;setTimeout(function(){P(a,!0)},c);a.F<G.g.Ha&&(a.F+=a.P,a.P*=2)}};a.c.onreadystatechange=function(){if(4==a.c.readyState)if(404==a.c.status)Q(a,"Server responded with code "+a.c.status+".");else{var c=a.c.getResponseHeader(G.g.ma);c&&(a.fa=
c);if(200!=a.c.status)a.o="Server responded with code "+a.c.status+".",a.c.onerror();else{c=a.c.responseText;var d=!1;9<c.length&&"while(1);"==c.substr(0,9)?(c=c.substr(9),d=!0):5<c.length&&")]}',"==c.substr(0,5)&&(c=c.substr(5),d=!0);if(d)if(c)try{c=JSON.parse(c)}catch(g){Q(a,"Failed to parse XHR data: "+a.c.responseText.substr(0,50)+"...");return}else c=null;c&&d&&"object"==typeof c.errors&&1<=c.errors.length&&"undefined"!==typeof c.severe&&1==c.severe?(a.o=c.errors[0],a.c.onerror()):(c={data:c},
a.c.getResponseHeader("Auth-Required")&&(c.authRequired=!0),Q(a,null,c))}}};a.c.open(c.method,c.url,!0);c.withCredentials&&(a.c.withCredentials=!0);var e=c.ta;"object"==typeof c.ta?(a.c.setRequestHeader("Content-type","application/json;charset=UTF-8"),e=JSON.stringify(e)):"POST"==c.method&&a.c.setRequestHeader("Content-type","application/x-www-form-urlencoded");"POST"==c.method&&a.fa&&a.c.setRequestHeader(G.g.ma,a.fa);a.c.send(e)}}
function R(a){a.c&&(a.c.abort(),a.c=null);a.Z=!1;a.F=G.g.ia;a.P=G.g.ja;a.O=0;a.R=0;a.o=null}function Q(a,c,d){var e=a.c&&a.c.status||0;R(a);setTimeout(function(){P(a)},0);if(0<a.H.length){var f=a.H.splice(0,1)[0];f.X&&(c?f.X({error:c,status:e}):f.X(d))}}G.g.i=function(){"undefined"===typeof G.oa&&(G.oa=new G.g);return G.oa};G=G||{};G.I="login";G.ya=1;G.S="install";G.xa=60;G.T="log";G.za=300;G.Fa=300;G.Ia=5E3;G.rb=1E3;G.ob=3;G.Ga=10;G.Ka="/ajax/log";G.Ja=2;G.qb="https://portal.synergyse.com/a/";G.Aa="chrome://newtab/";G.ka="medium version locale url category label uuid".split(" ");G.A={API_VERSION:"v",medium:"m",version:"mv",locale:"ul",url:"url",category:"c",label:"cl",uuid:"uid",appId:"app",eventTarget:"et",eventType:"ey",query:"qry",scriptId:"sid",contentId:"cid",results:"res",timeMs:"tms",uiType:"ui",userDomain:"ud"};
G.C=null;G.options=null;G.tabs={};G.m=0;G.storage=chrome.storage.sync;G.N=[];G.D={};G.L=null;G.debug=function(){};G.Pa=function(){var a=chrome.app.getDetails(),c=G.f.i().get("version");return a.version+"/"+(c?c:"0")};
G.Sa=function(a){var c=["width="+a.width,"height="+a.height,"left="+a.left,"top="+a.top,"toolbar=0,resizable=0,menubar=0,location=0,status=0,scrollbars=0"];G.debug("opening login window");G.Ta=window.open(a.url,"G Suite Training",c.join(","));chrome.alarms.clear(G.I);chrome.alarms.create(G.I,{periodInMinutes:G.ya});G.G&&clearInterval(G.G);G.G=setInterval(G.qa,G.Fa)};
G.qa=function(){G.Ta.closed&&(G.debug("login window closed, sending response"),chrome.alarms.clear(G.I),G.G&&(clearInterval(G.G),G.G=null),G.s&&(G.s({login:!0}),G.s=null))};G.W=function(a,c){G.da(function(){"simple"==G.options.runMode&&(G.g.i().ua=!0);G.g.i().send(a.hasPostData?"POST":"GET",a.url,a.params,c)})};G.gb=function(){null!==G.C&&(G.pa(G.C),G.C=null)};
G.pa=function(a){var c=document.getElementById("synergyse-clipboard");c||(c=document.createElement("textarea"),c.setAttribute("id","synergyse-clipboard"),document.body.appendChild(c));null===G.C&&(c.value="",c.focus(),document.execCommand("paste"),G.C=c.value,c.value="");c.value=a;c.focus();document.execCommand("selectAll");document.execCommand("copy");c.value=""};
G.Na=function(a){G.storage.get(G.a.B,function(c){if(chrome.runtime.lastError)return console.error("Failed to get UUID from storage."),a(null);if(Object.keys(c).length&&G.a.b(c,G.a.B)&&c[G.a.B])return G.u=c[G.a.B],a(G.u);G.u="";c=+new Date;for(var d=0;32>d;d++){var e=(c+16*Math.random()+Math.random())%16|0;c=Math.floor(c/16);G.u+=e.toString(16)}c={};c[G.a.B]=G.u;G.storage.set(c,function(){chrome.runtime.lastError&&console.error("Failed to store UUID to storage.")});a(G.u)})};
G.Oa=function(a){G.ea?a(G.ea):G.storage.get(G.a.K,function(c){if(chrome.runtime.lastError)return console.error("Failed to get UUID from storage."),a(null);if(Object.keys(c).length&&G.a.b(c,G.a.K)&&c[G.a.K])return G.ea=c[G.a.K],a(G.ea);a(null)})};G.wa=function(){var a=(new Date).setHours(0,0,0,0);if(!(0<G.m&&G.m>=a)){G.m=a;var c={};c[G.a.w]=a;G.storage.set(c,function(){chrome.runtime.lastError&&console.error("Failed to store LOGPING to storage.")})}};
G.Ua=function(){function a(){G.wa();G.ba({medium:"ext",category:"background",label:"ping"})}var c=(new Date).setHours(0,0,0,0);0<G.m?G.m<c&&a():G.storage.get(G.a.w,function(d){chrome.runtime.lastError?console.error("Failed to get LOGPING from storage."):Object.keys(d).length&&G.a.b(d,G.a.w)&&0<d[G.a.w]?(G.m=d[G.a.w],G.m<c&&a()):a()})};
G.ba=function(a){function c(c,e){var d={};d[G.A.API_VERSION]=G.Ja;for(var h=0,g=G.ka.length;h<g;h++){var m=G.ka[h];G.a.b(a,m)&&(d[G.A[m]]=a[m])}"undefined"!==typeof c&&c&&(d[G.A.uuid]=c);c=a.vars||[];"undefined"!==typeof e&&e&&c.push({name:"userDomain",type:"s",value:e});if(0<c.length)for(d.vn=c.length,h=0,g=c.length;h<g;h++)e="v"+h,m=c[h].name,"undefined"!==typeof G.A[m]&&(m=G.A[m]),d[e+"n"]=m,d[e+"t"]=c[h].type,d[e+"v"]=c[h].value;G.g.i().send("POST",G.a.M+G.Ka,d)}G.wa();G.da(function(){G.Na(function(d){G.Oa(function(e){G.a.b(a,
"version")?c(d,e):O(function(){a.version=G.Pa();c(d,e)})})})})};
chrome.extension.onMessage.addListener(function(a,c,d){if(a.ajax)return G.W(a,d),!0;if(a.checkPendingScript)return G.La(c.tab.id,d),!1;if(a.copy)return G.pa(a.value),!1;if(a.getDetails)return a=chrome.app.getDetails(),d({extensionVersion:a.version,extensionId:a.id}),!1;if(a.login)return G.debug("starting login"),G.s=d,G.Sa(a.loginData),!0;if(a.resetClipboard)return G.gb(),!1;if(a.serverLog)return G.ba(a),!1;if(a.optionsUpdated)return G.da(null,!0),!1;if(a.getConnectionPoolStatus)return G.Ma(d),!1;
if(a.retryConnection)return G.hb(),!1;console.error("G Suite Training: Unknown message received: "+JSON.stringify(a));return!1});chrome.runtime.onSuspend.addListener(function(){G.debug("Unloading background");G.s&&(G.s({loginFail:!0}),G.s=null)});
G.fb=function(){O(function(){chrome.tabs.query({},function(a){if(a){var c=I();a=a.slice();a.sort(function(a,d){a=G.a.Y(c,a.url);d=G.a.Y(c,d.url);if(a==d)return 0;if(a&&d)if("mail"!=a&&"inbox"!=a||"mail"!=d&&"inbox"!=d){if("mail"==a||"inbox"==a)return-1;if("mail"==d||"inbox"==d)return 1}else return 0;else{if(a)return-1;if(d)return 1}return a.localeCompare(d)});for(var d=0,e=0,f=a.length;e<f;e++){var h=a[e];G.a.Y(c,h.url)&&(chrome.tabs.reload(h.id),d++);if(d>=G.Ga)break}}})},!0)};
G.Xa=function(){G.fb();G.va()};G.Ya=function(){G.va()};G.va=function(){G.storage.get(G.a.v,function(a){chrome.runtime.lastError?console.error("Failed to get install timestamp from storage."):Object.keys(a).length&&G.a.b(a,G.a.v)&&a[G.a.v]||(a={},a[G.a.v]=+new Date,G.storage.set(a,function(){chrome.runtime.lastError&&console.error("Failed to store installation time to storage.")}))})};
G.La=function(a,c){G.tabs[a]&&(c(G.tabs[a]),G.tabs[a].timeout&&(clearTimeout(G.tabs[a].timeout),G.tabs[a].timeout=null),G.tabs[a].timeout=setTimeout(function(){delete G.tabs[a]},G.Ia))};G.da=function(a,c){var d=a||function(){};if(!c){if(G.options){d();return}G.options={}}G.storage.get(G.a.U,function(a){Object.keys(a).length&&G.a.b(a,G.a.U)&&(G.options=a[G.a.U],"dev"==G.options.runMode&&(console.log("Development mode"),G.sb=!0),G.a.lb());d()})};
G.Ma=function(a){var c=G.g.i();a({lastRequestStartTimeMs:c.O,nextRetryTimeMs:c.R,lastError:c.o})};G.hb=function(){var a=G.g.i();R(a);P(a,!0)};G.Va=function(a,c,d,e,f){var h=e||{},g=f||{};O(function(){for(var e=H(G.f.i(),"domain-"+a),f=[],u=0,l=e.length;u<l;u++)f.push("*://"+e[u]+"/*");f.length?chrome.tabs.query({url:f},function(a){1>a.length?g():(h(),chrome.tabs.update(a[0].id,{selected:!0},function(a){chrome.tabs.sendMessage(a.id,{action:"autostart",scriptId:c,time:d?d:0})}))}):g()})};
G.Wa=function(a,c){O(function(){var d=H(G.f.i(),"domain-"+a);d&&chrome.tabs.update(c,{url:"https://"+d[0]})})};G.ra=function(a){a&&a.active&&a.url&&!G.a.aa(a.url)&&(G.L=a.url)};chrome.alarms.onAlarm.addListener(function(a){if(a.name==G.I)G.qa();else if(a.name==G.T)G.Ua();else if(a.name==G.S){a=0;for(var c=G.N.length;a<c;a++){var d={medium:"ext",category:"background"};d.label=G.N[a];G.ba(d)}G.N=[]}});chrome.tabs.onCreated.addListener(function(a){a.url?G.a.aa(a.url)&&(G.D[a.id]=1):G.D[a.id]=1});
chrome.tabs.onUpdated.addListener(function(a,c,d){d.active&&G.ra(d);if("loading"===c.status&&G.a.aa(d.url)&&(c=G.a.Za(d.url),(!G.a.b(c,G.a.ha)||1!=c[G.a.ha])&&c.app&&c.script)){var e=c.app;d=c.script;var f=c.t;G.tabs[a]={sectionId:c.section,scriptId:d,time:f?f:0};G.Va(e,d,f,function(){G.a.b(G.D,a)||G.L==G.Aa?chrome.tabs.remove(a):G.L&&chrome.tabs.update(a,{selected:!1,url:G.L})},function(){G.Wa(e,a)})}});chrome.tabs.onActivated.addListener(function(a){chrome.tabs.get(a.tabId,function(a){G.ra(a)})});
chrome.tabs.onRemoved.addListener(function(a){G.a.b(G.D,a)&&delete G.D[a]});chrome.runtime.onInstalled.addListener(function(a){G.a.b(a,"reason")&&("install"==a.reason?G.Xa():"update"==a.reason&&G.Ya(),G.N.push(a.reason),a=Math.round(Math.random()*G.xa),chrome.alarms.clear(G.S),chrome.alarms.create(G.S,{delayInMinutes:a}));a=Math.round((1.2-.4*Math.random())*G.za);chrome.alarms.clear(G.T);chrome.alarms.create(G.T,{periodInMinutes:a})});chrome.runtime.onConnect.addListener(function(){});
