var e="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function h(){h=function(){};g.Symbol||(g.Symbol=k)}var k=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function l(){h();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&e(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return m(this)}});l=function(){}}function m(a){var b=0;return n(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function n(a){l();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}
function p(a,b){l();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}function q(a){if(a){for(var b=g,c=["Array","prototype","keys"],d=0;d<c.length-1;d++){var f=c[d];f in b||(b[f]={});b=b[f]}c=c[c.length-1];d=b[c];a=a(d);a!=d&&null!=a&&e(b,c,{configurable:!0,writable:!0,value:a})}}
q(function(a){return a?a:function(){return p(this,function(a){return a})}});var r,t,u,v="",w=!1;
function x(){var a={};a.disableMenu=1==document.getElementById("disable-menu").value;a.showHiddenOptions=w?1:0;a.serverAddress=document.getElementById("server-address").value||"";a.runMode=document.getElementById("run-mode").value||"prod";a.recordMode=1==document.getElementById("record-mode").value;a.autopilot=1==document.getElementById("autopilot").value;a.enableMenuHover=1==document.getElementById("menu-hover").value;a.forceUserLikeNew=1==document.getElementById("force-new").value;if(a.serverAddress&&
0!=a.serverAddress.indexOf("http"))y("Server Address Error");else{var b={};b.options=a;r.set(b,function(){y("Saved!");chrome.extension.sendMessage({optionsUpdated:!0})})}}
function z(){r.get("options",function(a){Object.keys(a).length&&"undefined"!==typeof a.options&&(a=a.options,document.getElementById("disable-menu").value=a.disableMenu?1:0,document.getElementById("disable-menu-warning").style.display=a.disableMenu?"inline-block":"none",document.getElementById("server-address").value=a.serverAddress||"",document.getElementById("run-mode").value=a.runMode||"prod",document.getElementById("record-mode").value=a.recordMode?1:0,document.getElementById("autopilot").value=
a.autopilot?1:0,document.getElementById("menu-hover").value=a.enableMenuHover?1:0,document.getElementById("force-new").value=a.fcrceUserLikeNew?1:0,a.showHiddenOptions&&(w=1,t.style.display="block"))});var a=chrome.runtime.getManifest();document.getElementById("build-version").innerHTML=a.version}function y(a){var b=document.getElementById("status");b.textContent=" - "+a;setTimeout(function(){b.textContent=""},3E3)}r=chrome.storage.sync;t=document.getElementById("hidden-options");
t.style.display="none";document.getElementById("disable-menu").addEventListener("change",function(){var a=document.getElementById("disable-menu");1!=a.value||confirm("This will prevent you from accessing training content going forward including any current and future lessons. Are you sure?")||(a.value=0);document.getElementById("disable-menu-warning").style.display=1==a.value?"inline-block":"none";document.getElementById("disable-menu-tip").style.display=1==a.value?"block":"none"});
document.getElementById("hide-options").addEventListener("click",function(){t.style.display="none";v="";w=!1;x()});document.addEventListener("DOMContentLoaded",z);document.addEventListener("keydown",function(a){v+=String.fromCharCode(a.which);0<=v.indexOf("SYNERGYSE")?(t.style.display="block",v="",w=!0,x()):(clearTimeout(u),u=setTimeout(function(){v=""},1E3))});document.getElementById("save").addEventListener("click",x);document.getElementById("cancel").addEventListener("click",z);
